### ISSUE TITLE
Reduce the amount of information persisted in deployed solution item data

### ISSUE THREAD

**Issue by chris-fox** [Esri/solution.js#101]
@MikeTschudi, @jmhauck, Currently in a deployed solution we are still storing the full item details and data definition with the deployed solution. I think we should minimize this to the minimum required to support the solution contents tree. At this point it seems like all that is would be the templates array with a series of objects with an item id and a list of dependencies.

Thoughts?

**Comment by MikeTschudi** [comment]
That was an idea that we started with (it's even in the main README!) but moved away from; I don't recall why. OK with me to reduce the deployed solution item.

**Comment by jmhauck** [comment]
Same here...I'm cool with reducing it

**Comment by chris-fox** [comment]
@jmhauck, Could we simplify the deployed Solution item to the json below? Each template has an itemId, type, and dependencies property. Ideally we wouldn't need the empty item propety, but I find the Solution Contents fails to load without it. Maybe we could remove this requirement for March?

{
    "templates": [
        {
            "itemId": "96c86ef8e30b45c0985addcfce2647d9",
            "type": "Group",
            "dependencies": [
                "160fce6da47849559a54b361236713b7",
                "34684f3ee2bc42979204d1c184fd7db6",
                "cf69c4a1152246419e25a94bc3a52381",
                "cd85a2bff3cb4d308c062a681b859c9a",
                "b9414c68c341415a8e626aa8e1b0c466",
                "87741cf3e2dd4f55a46d03a0ee118c09",
                "50b39d1578df445db19b98dd4e2ecbe9",
                "4db5cd6b84ed4c949c3d80bfcdfa2d4c",
                "38c5a9b828514164aa764ed39d637645"
            ],
            "item": {}
        },
        {
            "itemId": "94203edb9d2b4af88449eee7b4b3ffc0",
            "type": "Feature Service",
            "dependencies": [
				"96c86ef8e30b45c0985addcfce2647d9"
			],
            "item": {}
        },
        {
            "itemId": "41619af111824e7386632984342d7654",
            "type": "Web Mapping Application",
            "dependencies": [
                "96c86ef8e30b45c0985addcfce2647d9"
            ],
            "item": {}
        },
        {
            "itemId": "e49b45140fc649c99b3c6e1e8d5296e4",
            "type": "Feature Service",
            "dependencies": [
                "94203edb9d2b4af88449eee7b4b3ffc0"
            ],
            "item": {}
        },
        {
            "itemId": "8be46fdac01b4732baf03a0842b4b727",
            "type": "Feature Service",
            "dependencies": [
                "94203edb9d2b4af88449eee7b4b3ffc0"
            ],
            "item": {}
        },
        {
            "itemId": "371660bac4004a0aa2796967fdb31644",
            "type": "Feature Service",
            "dependencies": [
                "94203edb9d2b4af88449eee7b4b3ffc0"
            ],
            "item": {}
        },
        {
            "itemId": "91b48c73e4f0422aa4122f24199565b0",
            "type": "Feature Service",
            "dependencies": [
                "94203edb9d2b4af88449eee7b4b3ffc0"
            ],
            "item": {}
        },
        {
            "itemId": "b77bffacd88c41b0b24109b07979037e",
            "type": "Feature Service",
            "dependencies": [
                "94203edb9d2b4af88449eee7b4b3ffc0"
            ],
            "item": {}
        },
        {
            "itemId": "00e9559ab95d450e8a0c70beecac5632",
            "type": "Feature Service",
            "dependencies": [
                "94203edb9d2b4af88449eee7b4b3ffc0"
            ],
            "item": {}
        },
        {
            "itemId": "f9aa8fbd7fed4813bae51f513564c7b0",
            "type": "Feature Service",
            "dependencies": [
                "94203edb9d2b4af88449eee7b4b3ffc0"
            ],
            "item": {}
        },
        {
            "itemId": "9f2df44b4eec41d495f35ce9f7a45e98",
            "type": "Feature Service",
            "dependencies": [
                "94203edb9d2b4af88449eee7b4b3ffc0"
            ],
            "item": {}
        },
        {
            "itemId": "ece87af094184acd8808d08d4aa42212",
            "type": "Feature Service",
            "dependencies": [
                "94203edb9d2b4af88449eee7b4b3ffc0"
            ],
            "item": {}
        },
        {
            "itemId": "160fce6da47849559a54b361236713b7",
            "type": "Web Map",
            "dependencies": [
                "e49b45140fc649c99b3c6e1e8d5296e4"
            ],
            "item": {}
        },
        {
            "itemId": "34684f3ee2bc42979204d1c184fd7db6",
            "type": "Web Map",
            "dependencies": [
                "8be46fdac01b4732baf03a0842b4b727"
            ],
            "item": {}
        },
        {
            "itemId": "cf69c4a1152246419e25a94bc3a52381",
            "type": "Web Map",
            "dependencies": [
                "371660bac4004a0aa2796967fdb31644"
            ],
            "item": {}
        },
        {
            "itemId": "cd85a2bff3cb4d308c062a681b859c9a",
            "type": "Web Map",
            "dependencies": [
                "91b48c73e4f0422aa4122f24199565b0"
            ],
            "item": {}
        },
        {
            "itemId": "b9414c68c341415a8e626aa8e1b0c466",
            "type": "Web Map",
            "dependencies": [
                "b77bffacd88c41b0b24109b07979037e"
            ],
            "item": {}
        },
        {
            "itemId": "87741cf3e2dd4f55a46d03a0ee118c09",
            "type": "Web Map",
            "dependencies": [
                "00e9559ab95d450e8a0c70beecac5632"
            ],
            "item": {}
        },
        {
            "itemId": "50b39d1578df445db19b98dd4e2ecbe9",
            "type": "Web Map",
            "dependencies": [
                "f9aa8fbd7fed4813bae51f513564c7b0"
            ],
            "item": {}
        },
        {
            "itemId": "4db5cd6b84ed4c949c3d80bfcdfa2d4c",
            "type": "Web Map",
            "dependencies": [
                "9f2df44b4eec41d495f35ce9f7a45e98"
            ],
            "item": {}
        },
        {
            "itemId": "38c5a9b828514164aa764ed39d637645",
            "type": "Web Map",
            "dependencies": [
                "ece87af094184acd8808d08d4aa42212"
            ],
            "item": {}
        }
    ]
}

**Comment by chris-fox** [comment]
Verified
