### ISSUE TITLE
Support new subtype layers

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/solution.js#1040]
`subtype-group` and `subtype-sublayer`

**Comment by chris-fox** [comment]
@MikeTschudi, I was doing some testing on this today and I was able to create a solution using a web map containing a subtype group layer and several subtype sublayers. It successfully packaged the web map and associated hosted feature service. The correct variables were templatized. When I deployed, everything deployed successfully and the subtype group layer behaved as expected. So this looks like it is already working properly, it seems to just behave like any other feature service and operational layer in the web map.

Below is a test map if you want to take a look, but it seems like we can close this issue as already implemented.

https://localdeployment.maps.arcgis.com/apps/mapviewer/index.html?webmap=e4656fea247d41a683b7d38e3b9ef7cc

**Comment by MikeTschudi** [comment]
What delightful news--thanks, @chris-fox!  The solution looks good to me, too.

Interesting map as well.  :-)
