### ISSUE TITLE
Discover webmap referenced in QuickCapture projects during creation

### ISSUE THREAD

**Issue by chris-fox** [Esri/solution.js#1046]
QuickCapture projects can reference a webmap, we should pull this automatically when creating a new solution. It is reference like below in the item. We should check if the type is WebMap and then can use the itemId property to discover it.

{
    "basemap": {
        "type": "WebMap",
        "itemId": "3899c47412024f5cb3278e531bfbbf20",
        "mapAreas": [],
        "required": true,
        "useDefaultBasemap": false,
        "zoomLevel": null
    }

You can test with this QuickCapture item: https://localdeployment.maps.arcgis.com/home/item.html?id=62ad564a5104437eac605b73b55ebf51

**Comment by shoe913** [comment]
Verified
