### ISSUE TITLE
View referencing fields in the source that based on statistics are being removed

### ISSUE THREAD

**Issue by chris-fox** [Esri/solution.js#1047]
When deploying to enterprise if you have a view that is referencing fields in a source view that were generated from statistics those fields are dropped in the addToDefinition for the layer.

1. Deploy this item to Enterprise: f6f08c93252a41ba8d45538012ab2ded
2. The resulting Gravesites_labels view is missing the burialcount, fullname1, and fullname2 fields

The solution has 3 feature layers (1 feature service and 2 views). The Gravesite_burials view has a table id 1 that has some fields defined as statistics, these fields don't exist in the source service, they are dynamically generated and have a property statisticType.
```
 "sourceLayerFields" : [
          {
            "name" : "parentglobalid", 
            "alias" : "Parent Global ID", 
            "source" : "parentglobalid"
          }, 
          {
            "name" : "burialcount", 
            "alias" : "Burial Count", 
            "source" : "parentglobalid", 
            "statisticType" : "COUNT"
          }, 
          {
            "name" : "fullname1", 
            "alias" : "Full Name 1", 
            "source" : "fullname", 
            "statisticType" : "MIN"
          }, 
          {
            "name" : "fullname2", 
            "alias" : "Full Name 2", 
            "source" : "fullname", 
            "statisticType" : "MAX"
          }
        ]
```

The Gravesites_labels view has a layer that on the right-side of the join uses the table above as a source and references those statistic fields of burialcount, fullname1, and fullname2.
```
"relatedTables" : [
          {
            "name" : "Cemeteries_StatsTable", 
            "sourceServiceName" : "Gravesites_burials_dd6da282de23402ba4b82e4ca0370536", 
            "sourceLayerId" : 1, 
            "sourceId" : 98822, 
            "sourceLayerFields" : [
              {
                "name" : "parentglobalid", 
                "alias" : "Parent Global ID", 
                "source" : "parentglobalid"
              }, 
              {
                "name" : "burialcount", 
                "alias" : "Burial Count", 
                "source" : "burialcount"
              }, 
              {
                "name" : "fullname1", 
                "alias" : "Full Name 1", 
                "source" : "fullname1"
              }, 
              {
                "name" : "fullname2", 
                "alias" : "Full Name 2", 
                "source" : "fullname2"
              }
            ], 
            "type" : "LEFT", 
            "parentKeyFields" : ["globalid"], 
            "keyFields" : ["parentglobalid"], 
            "operator" : "EQUALS"
          }
        ]
```
Those fields are dropped in the addToDefinition when creating the layer in the Gravesites_labels view in Enterprise. This is not an issue in ArcGIS Online.

**Comment by jmhauck** [comment]
@chris-fox when we first discussed this you mentioned the possibility of needed to account for fields with an expression prop. Is this still the case?

**Comment by chris-fox** [comment]
@jmhauck, when there is an expression prop, you still need to provide a source field. See below the last field is based on an expression. That being said will there be a problem if a view is built on this view and it looks for a field called density in the source service but doesn't exist?

```
"sourceLayerFields": [{
				"name": "OBJECTID",
				"alias": "OBJECTID",
				"source": "OBJECTID"
},{
				"name": "name",
				"alias": "Name",
				"source": "name"
},{
				"name": "population",
				"alias": "Population",
				"source": "population"
}, {
				"name": "area",
				"alias": "Area",
				"source": "area"
}, {
				"name": "density",
				"alias": "Density",
				"expression": "population / area",
				"type": "esriFieldTypeDouble",
				"source": "population"
}]                                                                           
```

Also it brings up another question. It is possible for me to rename a field in a view. 

```
sourceLayerFields": [{
				"name": "OBJECTID",
				"alias": "OBJECTID",
				"source": "OBJECTID"
},{
				"name": "name1",
				"alias": "Name",
				"source": "name"
}]                                                                           
```
Will this cause issues if another view is built on top of this view and references the field "name1"? I guess I am not sure why we need to trace back all the way to the source feature service to see if the field exists, really the field just need to exist in the source of each view.

**Comment by jmhauck** [comment]
@chris-fox could we chat when you are back in...I'm not seeing how to create these situations. When I try to make similar edits via rest API they don't stick.

**Comment by chris-fox** [comment]
@jmhauck, expression based fields are not supported in Enterprise yet, so this is not a valid case for this issue. I was able to build the item below and tested in ArcGIS Online and everything is working as expected. 

e70e8d56824145b1a3c8356f51bf56f8
