### ISSUE TITLE
View fails to deploy if a layer has a source to a different layer or table in the same service

### ISSUE THREAD

**Issue by chris-fox** [Esri/solution.js#1048]
Deploy the following item, it will fail on the addToDefinition for the view.

e70e8d56824145b1a3c8356f51bf56f8

In this solution there are 2 feature layers (1 source service and 1 view). The view has 1 layer (id 1) and 1 table (id 0). Table id 0 is pointing to the source service. Layer id 1 is a join view between a layer in the source service and the table id 0 in the view service. The issue is when creating the view it is attempting to add Layer id 1 first before Table id 0 has been added and this causes it to fail.

In these scenarios when a layer or table references a layer or table in the same feature layer or view we need to process them in order to ensure all the sources are added first.

**Comment by jmhauck** [comment]
@chris-fox can the id be used for sorting or just circumstance that we want id 0 first in this case?

**Comment by jmhauck** [comment]
And thanks for the info on using IDs...I had added a topological sort that looked through what was related to what and defined the order that way...similar to what we do for defining the overall build order but IDs will be easier.

**Comment by chris-fox** [comment]
The original item can no be successfully deployed, but I am encountering a similar issue in a different solution item that is still failing because the layers/tables are being added in the wrong order.

2f3b031686c347f9be27cc84ee2a8739

**Comment by chris-fox** [comment]
Verified
