### ISSUE TITLE
Look under new properties to discover Dashboard dependencies

### ISSUE THREAD

**Issue by chris-fox** [Esri/solution.js#1049]
In the most recent update the properties we looked for dependencies, 'widgets', 'headers', 'sidebar' may now display under a 'desktopView' or 'mobileView' property rather than the root of the item data. Could we update the logic to also look under 'desktopView' and 'mobileView' for these properties and process them just like we did previously when they were at the root.

Below is an example Dashboard with this configuration, if you attempt to just create a solution from the Dashboard it will not discover the web map that is referenced in the item data:

https://localdeployment.maps.arcgis.com/home/item.html?id=22989d334e174f6fbeb24cfaf6a583c0

**Comment by chris-fox** [comment]
@MikeTschudi, there was a regression with this. If you create a solution from this item:

https://localdeployment.maps.arcgis.com/home/item.html?id=67f383b2d65b4780bcafac3e78b84a45

It is turning this datasource under the widgets property from:
```
                        "dataSource": {
                            "type": "layerDataSource",
                            "itemId": "e9e4d885aa41470bb0ea35627a8fa111",
                            "layerId": "17da119ef1c-layer-5"
                        }
```
to:
```
                        "dataSource": {
                            "type": "layerDataSource",
                            "itemId": "{{e9e4d885aa41470bb0ea35627a8fa111.layer17da119ef1c-layer-5.itemId}}",
                            "layerId": "{{e9e4d885aa41470bb0ea35627a8fa111.layer17da119ef1c-layer-5.layerId}}"
                        },
```
This is incorrect, it shouldn't be taking be replacing the layerId property and should actually create this:
```
                        "dataSource": {
                            "type": "layerDataSource",
                            "itemId": "{{e9e4d885aa41470bb0ea35627a8fa111.itemId}}",
                            "layerId": "layer17da119ef1c-layer-5"
                        },
```

**Comment by MikeTschudi** [comment]
Updated via commit 03404ea23485d04c229944c11f3eca4eeb338b09

**Comment by shoe913** [comment]
Verified

**Comment by shoe913** [comment]
@MikeTschudi , looks like this may still be an issue with Arcade References. 

If you create a solution item with this dashboard, line 438 is getting a variable substitution it shouldn't be 

https://localdeployment.maps.arcgis.com/home/item.html?id=87b73146024942fc90fa076fb6060747

**Comment by MikeTschudi** [comment]
@shoe913, OK, shouldn't go from
![image](https://github.com/Esri/solution.js/assets/2125181/da21e9e9-bf5d-4306-a01c-7f02500af757)
to
![image](https://github.com/Esri/solution.js/assets/2125181/53fd9aa3-8cdd-446b-b076-fc4831ad47f6)

What is the general rule, please?  Never templatize a dataset with the type "serviceDataset"? Never templatize anything in the property `datasets`? Something else?

**Comment by chris-fox** [comment]
@MikeTschudi, I see 3 different ways a data source is referenced via a non-map widget:

Layer in a web map, we should templatize the itemId property:
```
                    {
                        "type": "serviceDataset",
                        "name": "main",
                        "dataSource": {
                            "type": "layerDataSource",
                            "itemId": "2e3db7d2d13c49ed95db73b00776a48a",
                            "layerId": "18853e767e9-layer-2"
                        }, 
```

Layer from a hosted feature service, we should templatize the itemId property:
```
                    {
                        "type": "serviceDataset",
                        "name": "main",
                        "dataSource": {
                            "type": "layerDataSource",
                            "itemId": "38b6998cabbf44acb5fe1eba02b513d0",
                            "layerId": 0
                        },
```

An arcade expression, we should not templatixe the itemId property
```
                    {
                        "type": "serviceDataset",
                        "name": "main",
                        "dataSource": {
                            "type": "arcadeDataSource",
                            "itemId": "3f281598-2571-42c8-9fe7-fa7d18819bc3"
                        },
```
So it seems like we can ignore if the type of the dataSource object is 'arcadeDataSource'

**Comment by MikeTschudi** [comment]
Thank you, @chris-fox!

**Comment by MikeTschudi** [comment]
@chris-fox, @shoe913, all of the items in https://github.com/Esri/solution.js/issues/1049#issuecomment-1518278928
are of type "layerDataSource"; how should I differentiate which to templatize, please?

**Comment by chris-fox** [comment]
@MikeTschudi, That comment was referring to the "layerId" property. This property does not need to be templatized. The only property you need to templatize in the dataSource object that are of type "layerDataSource" is the "itemId" property.

**Comment by MikeTschudi** [comment]
Thank you, @chris-fox; I'd missed the distinction.
