### ISSUE TITLE
disableDiscussions setting is not being set when deploying Hub sites

### ISSUE THREAD

**Issue by chris-fox** [Esri/solution.js#1050]
Not sure if this requires a change in Hub.js. in the template json we are adding "disableDiscussions" to values.capabilities:

```
"capabilities": [
            "api_explorer",
            "pages",
            "my_data",
            "social_logins",
            "json_chart_card",
            "document_iframes",
            "items_view",
            "app_page",
            "underlinedLinks",
            "globalNav",
            "socialSharing",
            "disableDiscussions"
        ]
```
This exists in the template solution item, but when deploying this value is removed from the payload to addItem when creating the site. We would like to persist this setting when deploying the site. You can reproduce this issue with the solution item:

e3d4166191d84513bfe796bcc0ac3280

The template 'Quality Roads' has this setting, but when deployed it is stripped.

**Comment by MikeTschudi** [comment]
@chris-fox, this setting is in hub.js, and I'm working on contributing it.

**Comment by MikeTschudi** [comment]
Available via hub.js update in #1087

**Comment by MikeTschudi** [comment]
Branch https://github.com/esri/solution.js/tree/ch/1050-disableDiscussions adds deploySolution demo for testing this fix.

**Comment by shoe913** [comment]
Verified
