### ISSUE TITLE
Update to latest hub.js

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/solution.js#1069]
Modified to support latest hub.js

* [x] solution.js

#### solution.js demos
* [x] compareJSON
* [ ] convertExtent
* [x] copyItemInfo
* [x] copySolutions
* [ ] createFolder
* [x] createSolution
* [x] deleteSolution
* [x] deploySolution
* [ ] deploySolutionCustom
* [ ] getGroupInfo
* [ ] getItemHierarchy
* [x] getItemInfo
* [ ] getPortalInfo
* [ ] implementedTypes
* [ ] polyfillExplorer
* [ ] sanitizeGroupItems
* [ ] sanitizer
* [ ] searchGroupCategories
* [ ] templatization
* [x] verifySolution

**Comment by shoe913** [comment]
Verified
