### ISSUE TITLE
Templatize spatial reference of feature services to allow users to optionally provide their own spatialReference

### ISSUE THREAD

**Issue by chris-fox** [Esri/solution.js#110]
For any spatialReference object in feature services we should replace with the following variable:

{{spatialReference||{"wkid" : 102100, "latestWkid" : 3857 }}}

The fallback value would be the original spatial reference of the service. If the user provides a spatialReference for the deployment we can apply it when the service is created otherwise it uses the original spatial reference.

**Comment by chris-fox** [comment]
@jmhauck, could you take a look at this one. We don't need to do anything special when creating the template. I just want to allow template authors to manually insert this variable to allow the spatial reference to be customized on deployment. Could you look into this to see if there is anything special we need to do to support this?

**Comment by jmhauck** [comment]
@chris-fox Could we chat on this when you have a few? Maybe I’m missing something. Currently the template dictionary we use for replacement is built during deployment. Will the end user deploying have some opportunity to control values that are defined in the template dictionary? Does this tie into the idea of what hub does? 

In general I'm not seeing a clean way to do exactly as listed above. I thought maybe we could use transforms but those are not applied to static/fallback values and static values can only come back as string float or int. So for the example above our source spatial reference would come back as a string of "wkid : 102100, latestWkid : 3857" and that does us no good.

However, we could target the more simple value of the wkid for example:

```json
spatialReference: {
   "wkid": "{{wkid||102100}}"
}
```

**Comment by chris-fox** [comment]
@jmhauck, sorry I was out of the office yesterday. We can talk more today, I do have a plan for users to be able to specify their own parameters prior to deployment and we would need to be able to pass the api when deploying a template. So we just need to think about what we should be able to pass. This was similar to our conversation about users passing in their own extent when deploying a template.

**Comment by jmhauck** [comment]
This allows us to do the following...

Inside one of the templates we can create custom templatization options:
 
```javascript
{{ params.someProperty.value }}
```

For any swapping to take place the solution items data will need to contain a supporting params object:

```javascript
{
  templates: [...],
  metadata: {},
  params: {
    someProperty: {
      value: "The Value We Want",
      type: "Text"
    }
  }
}
```

After the inital params object the structure is dynamic. The value/type pair is an example of what we could consider to support both the value swapping as well as the dynamic UI support for user input.

**Comment by shoe913** [comment]
@chris-fox @jmhauck 

Not 100% sure what I should be looking for in here. From the conversation above, it sounds like a UI may be needed to see the changes. 

Currently my template item does not appear to have double brackets for a variable in the JSON. Would I expect to see double brackets or just standard JSON for spatial reference?

**Comment by jmhauck** [comment]
@shoe913 yes, the goal would be to have some UI to support this. For now the only way you could test is to manually edit the solution item. I'd be happy to step through it a bit with you in a few if you like.

**Comment by chris-fox** [comment]
I think we can just close this out and re-visit when we are ready to implement the user defined variables.

**Comment by shoe913** [comment]
Cool, will close this for now and revisit when we're ready for user variables.
