### ISSUE TITLE
Don't package the draft.json resource of a Hub site

### ISSUE THREAD

**Issue by chris-fox** [Esri/solution.js#1102]
In Hub sites you can create a draft to store changes before you publish the site and make available to non-editors. This is stored in a draft.json resource file. This file is not swizzled during solution creation, so when it is copied with the site if the user edits the site once deployed they see references to old items and info products. We should not include this draft.json file when creatine a solution from a Hub site. It is not required for the deployment.

**Comment by shoe913** [comment]
Verified
