### ISSUE TITLE
Hub Site Registration failing

### ISSUE THREAD

**Issue by shoe913** [Esri/solution.js#1117]
When creating a Hub Site with solution.JS, the app fails to register. 

This prevents solution deployment and in conjunction with #1116 prevents content from being fully deleted on failure or after creation. 

![image](https://github.com/Esri/solution.js/assets/11777080/69e6c1e0-ab56-4a93-a17e-3dd030020fd0)

**Comment by chris-fox** [comment]
This was resolved by the Hub team
