### ISSUE TITLE
Add Python Notebook item type

### ISSUE THREAD

**Issue by chris-fox** [Esri/solution.js#112]
New item type in ArcGIS Online and Enterprise. A .ipynb is stored with the item which is a simple text item that need to be copied when cloned.

Would like to explore templatizing any item id references in the .ipynb and swizzling when we deploy the notebook as we plan on using this item to automate workflows with related items as part of a solution.

**Comment by jmhauck** [comment]
@shoe913 we are just doing item ids for now

**Comment by shoe913** [comment]
@jmhauck  Cool, I'll test this tomorrow when everything refreshes. 

Will I need to use the {{ pattern to switch Item Ids in here or will the notebook be scanned and then flipped automatically?

**Comment by jmhauck** [comment]
@shoe913 you can test now. No additional changes were needed from the previous commit I made awhile back.

The create/publish step will look for the itemIds referenced by the notbook and templatize them. You shouldn't need to update anything manually for them.

**Comment by shoe913** [comment]
Verified.

#176  Will take care of Solution Contents Icon missing
