### ISSUE TITLE
Duplicate but bogus resources listed when creating a Solution out of a Quick Capture Project

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/solution.js#1151]
When creating a Solution out of a QC project, solution.js pre-fetches its resources, but then runs the project through the same resource fetching that it does for other item types. The initial set is not in the correct format--they're files--and create a Solution that can't be deployed:
![image](https://github.com/Esri/solution.js/assets/2125181/a71ea99a-1143-4ef8-8792-e22f7dbe88f1)

**Comment by chris-fox** [comment]
Verified
