### ISSUE TITLE
Add Public Notification for ArcGIS Enterprise Variable

### ISSUE THREAD

**Issue by shoe913** [Esri/solution.js#1211]
When packaging a Public Notification Instant App from ArcGIS Online, the source ID is set as "4799f2bd805c4d7bab4cfc90c96e1c38".

For ArcGIS Enterprise this should be "4210be6cbc7b42f78274a1df37cdca57"

Can we have a new variable added in the same way we handle other instant apps (ex. Sidebar) for auto detecting and creating a variable on solution package.

**Comment by chris-fox** [comment]
@shoe913, we handle this in the download GP tool in the solution-items repo. See the lookup highlighted below. You should be able to add public notification there or work with @ted-howard to get it added.

https://devtopia.esri.com/WebGIS/solution-items/blob/master/src/soltools/common/settings.py#L8

**Comment by shoe913** [comment]
Moved to proper repository
