### ISSUE TITLE
Support group tag when creating a solution item

### ISSUE THREAD

**Issue by shoe913** [Esri/solution.js#1226]
During solution item creation, we need a way to allow solution authors to ship groups with the solution. 

During Solution Item creation, a tag will be added to the Solution group which will contain the group id of the desired group to add to the solution. 
example:     group.1eec18853f1942d480089f7102647fee

We'll need to read this tag during content discovery, and add then add the group's id to the list of content to package. Once packaged, we'll remove the tag from the Solution Item.

https://github.com/ArcGIS/solution-creation-app/issues/99

**Comment by MikeTschudi** [comment]
@shoe913, a double-check, please.  I have a group with a simple "Basic Viewer" map and a `group.8d515625ee9f49d7b4f6c6cb2a389151` tag. That id points to a group ("Critical Solution") that contains a "Map labels" map.  I create a solution using the first group and I get a solution with an embedded group.  Is this what you're looking for?

![image](https://github.com/Esri/solution.js/assets/2125181/a24d3abb-ad5d-49a3-b77b-b8946cb1f728)

**Comment by shoe913** [comment]
@MikeTschudi,  that is exactly what we're looking for!

**Comment by shoe913** [comment]
Verified
