### ISSUE TITLE
Question: source to be used for deploy.commonid & deploy.version 

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/solution.js#123]
Currently, individual items in a solution can have deploy.commonid & deploy.version defined. The group that contains the items used to construct a solution also has deploy.commonid & deploy.version defined.

When deploying a solution, should a single deploy.commonid & deploy.version be used, such as that of the group?  Do we require that all component items have matching deploy.commonid & deploy.version?  If so, what if an item is shared to multiple solution groups?  Should deploy.commonid & deploy.version be removed from component items?

**Comment by chris-fox** [comment]
@MikeTschudi, we don't need to worry about the individual items and their commonid and version tags.  A solution will have a single commonid and version. I am going to spend sometime this week thinking fully about the id and versioning workflow and discuss in a future meeting.
