### ISSUE TITLE
Deployed WAB has unresolved template variable

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/solution.js#124]
At the end of the WAB template is the template variable "appItemId", which is not replaced during deployment.

**Comment by chris-fox** [comment]
@chris-fox To provide more details

**Comment by jmhauck** [comment]
@chris-fox I took a quick look at the WAB source and this item id is used when you save changes to your WAB app and also used as a part of app registration.

**Comment by chris-fox** [comment]
@jmhauck, per our conversation whenever we templatized this property lets always set it to the item id of the template. This will handle cases were we have some apps that are incorrectly set to the wrong item id (bug in my python cloning code).

**Comment by chris-fox** [comment]
@jmhauck, I just tested this with the latest create app using the Election Outreach solution and I am still seeing the same issue. the appItemId is still pointing to the wrong item id variable. Could you check if you code made it to the latest app with the merge?

**Comment by jmhauck** [comment]
@chris-fox I should have read your comment closer. The change I made only affects deployment and sets the appItemId to be that of the newly created web app regardless of what's in the template.

**Comment by chris-fox** [comment]
Verified
