### ISSUE TITLE
Create utility app to copy template between portals

### ISSUE THREAD

**Issue by chris-fox** [Esri/solution.js#127]
During development we will be authoring solution templates in one org and need a way to copy the template to a different org/portal to be staged for the deployment gallery. 

So we need a site that has 2 logins, source and destination. We then need to be able to select a template in the source portal and copy it to the destination portal.

**Comment by MikeTschudi** [comment]
Added example for this via commit 6411c13084e85db9d7ee91acfa16cd9c77796685

**Comment by MikeTschudi** [comment]
@chris-fox, url is the same; nightly update script wasn't configured to build examples. It now does

**Comment by chris-fox** [comment]
Verified
