### ISSUE TITLE
Support templatizing and deploying item types with a download

### ISSUE THREAD

**Issue by chris-fox** [Esri/solution.js#128]
For any item types with a download we need to store the download as a resource of the solution item template and then support deploying that with the new created item as it download. Examples:

ArcGIS Pro Project Package
ArcGIS Pro Add In
Desktop Add In
Desktop Application Template
Geoprocessing Sample
Microsoft Word
PDF

**Comment by chris-fox** [comment]
@MikeTschudi, based on your comments on the Election Outreach project package failing to open in Pro 2.4, I tested it as well and found the resulting Pro Project item had no download. I checked the template and the pro project was not being stored in the item's resource, all I found were pngs for the thumbnails and other item resources. 

I wanted to capture this issue to handle all download item types.

**Comment by chris-fox** [comment]
@MikeTschudi, could you take a look at this issue next? I am not finding the download items types are properly having their downloads stored as resources in the template and as a result it is creating new items with no downloads.

**Comment by chris-fox** [comment]
@MikeTschudi, I created the Election Outreach solution today and found that the Solution Icon was being templatized and the Code Attachments for the WAB apps were also being templatized. I am assuming this is related to the work with this issue. Wondering if we could ignore Code Attachments during solution creation (We are already handling creating them for WAB during deployment). Also could we ignore the Solution Icon items (items specifically with the deploy.thumbnail tag).

**Comment by MikeTschudi** [comment]
@chris-fox, do I understand correctly that we'll not use the deploy.thumbnail experimental approach for Solution Icons? No more special-case items in group.

**Comment by chris-fox** [comment]
@MikeTschudi, I do still want to use the deploy.thumnail tagged item to generate the thumbnail for the Solution Item. The issue is in a recent update I found it is not doing this (The thumbnail is not being set) and it is also templatizing the item in the resulting solution item. I don't want this special thumbnail item included in the Solution Item templates. See highlighted below:

![image](https://user-images.githubusercontent.com/6796763/71118738-aaad6700-21a6-11ea-8343-9c6d2f8586b0.png)

**Comment by MikeTschudi** [comment]
Got it--thanks.  I removed it as part of creation rewrite and will restore it.

**Comment by chris-fox** [comment]
@MikeTschudi, I am not aware but I seem to be encountering a new issue w/ regard to deploying solutions referencing data items. When a solution has a template with a data item in it the deployment seems to stop before the final step of updating the final Solution item json, but seems to create everything correctly.

To repo deploy the "Election Results" solution from the test deployment app. I also have a template in the gallery called "Election Results w/ no data items" that is exactly the same as the "Election Results" except it doesn't have the logo png item in the template. This alternate item deploys successfully.

**Comment by MikeTschudi** [comment]
@chris-fox, thanks; I noticed it, too, with last night's test runs.

**Comment by shoe913** [comment]
Code attachments no longer coming trough as items and Pro Projects work after download. Resources section of JSON updated to contain the Project. 

Verified
