### ISSUE TITLE
Ability to define user variables and map to existing services/items in the org

### ISSUE THREAD

**Issue by chris-fox** [Esri/solution.js#129]
@MikeTschudi, @jmhauck 

The Hub team uses the pattern below to define their 'indicators'. These indicators are variables that need to be provided prior to deployment. For hub you can only define layer indicators, but I think we could use a similar pattern to define other custom variables. We could interrogate these variables and use them to present the UI for configuring the deployment of the solution.

Speaking with John today, in the current design we may have some challenges in supporting users providing layers that are potentially not in the same feature service as originally defined in the template. So we need to figure out an approach to this. The idea here is if the user provides a item we need to skip its creation and use it in an replacements where it is a dependency.

Finally, we need to support the ability to identify shared items that were created in previous deployments. In many solutions we will have shared services that we don't want to recreate as part of a deployment of another Solution. Currently we are discovering this in the Pro add-in by writing a type keyword to the new item that ties it to the original item. We need a similar mechanism to support Solutions templates that have shared services.

Wanted to give you both some time to think. Let's discuss further at a future meeting.

![image](https://user-images.githubusercontent.com/6796763/67242680-03b98280-f424-11e9-9c0f-38b0f3423507.png)

 "indicators": [
        {
            "id": "performanceBoundaries",
            "name": "Performance Boundaries",
            "type": "Data",
            "optional": false,
            "definition": {
                "supportedTypes": [
                    "FeatureLayer"
                ],
                "geometryTypes": [
                    "esriGeometryPolygon"
                ],
                "fields": [
                    {
                        "name": "Name",
                        "id": "name",
                        "supportedTypes": [
                            "esriFieldTypeString"
                        ],
                        "optional": false
                    }
                ]
            }
        },
        {
            "id": "performanceMetrics",
            "name": "Performance Metrics",
            "type": "Data",
            "optional": false,
            "definition": {
                "supportedTypes": [
                    "FeatureLayer"
                ],
                "geometryTypes": [
                    "esriGeometryPoint",
                    "esriGeometryPolyline",
                    "esriGeometryMultipoint",
                    "esriGeometryPolygon",
                    "esriGeometryLine"
                ],
                "fields": [
                    {
                        "name": "Boundary Name",
                        "id": "boundaryName",
                        "supportedTypes": [
                            "esriFieldTypeString"
                        ],
                        "optional": false
                    },
                    {
                        "name": "Date Reported",
                        "id": "dateReported",
                        "supportedTypes": [
                            "esriFieldTypeDate"
                        ],
                        "optional": false
                    },
                    {
                        "name": "Metric",
                        "id": "metric",
                        "supportedTypes": [
                            "esriFieldTypeString"
                        ],
                        "optional": false
                    },
                    {
                        "name": "Actual",
                        "id": "actual",
                        "supportedTypes": [
                            "esriFieldTypeDouble",
                            "esriFieldTypeInteger",
                            "esriFieldTypeSmallInteger",
                            "esriFieldTypeSingle"
                        ],
                        "optional": false
                    },
                    {
                        "name": "Target",
                        "id": "target",
                        "supportedTypes": [
                            "esriFieldTypeDouble",
                            "esriFieldTypeInteger",
                            "esriFieldTypeSmallInteger",
                            "esriFieldTypeSingle"
                        ],
                        "optional": false
                    }
                ]
            }
        }
    ]

**Comment by chris-fox** [comment]
@MikeTschudi, @jmhauck, as per our conversation this is how I propose we handle the shared use of items across solution templates:

Each template in the solution item has an "itemID' property:

"templates": [
        {
            "itemId": "2d2d176f5f3e43a985a31649e213aaf4",
            "type": "Web Mapping Application",

This is the same item id as the original item the template was created from. This item id is used to uniquely identify the template and its variables in the rest of the solution item. 

We will use this same property to uniquely identify templates across all solutions item templates. If there are templates in different solution items with the same item id they will be considered to be the same. This will be the case automatically when multiple solutions are authored from the same item.

When we deploy a solution to a user's organization we will create items from the templates. With each item we should write the a type keyword to the item associating it with the original template it was created from. It should follow this pattern:

"source-_itemID_" where itemID is the same as the property for the template, for example using above:

"source-2d2d176f5f3e43a985a31649e213aaf4"

Doing this allows us to deliver multiple Solutions that reference the same original items or templates and reuse those items during the deployment rather than create new ones. We can also be intelligent and present some UI to the user prior to deployment to allow them the option to reuse existing items or recreate new copies.

I will log a new issue to reflect this work and prioritize in backlog.

In addition, in conversation we decided we won't support users mapping individual layers in separate feature services from their org to a single feature service in a template. It adds a lot of complexity and in many scenarios Apps require a relationship between layers/tables within a single service that can't be broken apart.

For the indicators we need to have further discussions on this.

**Comment by chris-fox** [comment]
@MikeTschudi , @jmhauck, related to above I notice the template also has a property called "key". How is this created when the item is templatized and how is it used in the deployment?

"templates": [
        {
            "itemId": "2d2d176f5f3e43a985a31649e213aaf4",
            "type": "Web Mapping Application",
            "key": "yhk8oua3",

**Comment by MikeTschudi** [comment]
@chris-fox, the key is a random 8-character alphanumeric value beginning with a letter so that it can be used as a valid JavaScript identifier. It was requested by the Hub team; we don't use it.
