### ISSUE TITLE
Search for url encoded portal url and replace with {{portalBaseUrl}} property

### ISSUE THREAD

**Issue by chris-fox** [Esri/solution.js#1299]
This was discovered in relation to #1298. In story maps when you reference a survey123 form it stores the url in the item data as something like:

https://survey123.arcgis.com/share/?open=web&embed=fullScreen&portalUrl=https%3A%2F%2Flocaldeployment.maps.arcgis.com&id=6e5964fe33044f8cbc63ad9203ec5216&hide=navbar,footer,theme

The issue is when we create a solution the item id of the survey is properly swizzled, but the portalUrl (https%3A%2F%2Flocaldeployment.maps.arcgis.com) is not. As a result on deployment the survey does not work when deployed to a different portal/org.

In additional to search for the portal url on creation and replaceing with the {{portalBaseUrl}} variable is it possible to also search for the encoded representation of the url and replace with the {{portalBaseUrl}} variable as well?

Similar to #1298, you can use the group below to test this on the story map and story map briefing items:

https://localdeployment.maps.arcgis.com/home/group.html?id=b89df835727a42e7947eceb49dfa3f6d#overview

**Comment by MikeTschudi** [comment]
@chris-fox, I think that there may be other swizzling needed. In this case, it's for items referenced by the StoryMap.  With the example "Hello World" StoryMap, it's references to the "Citizen Problem Manager" WMA and "Favorite Redlands Restaurant" Form, respectively:

![image](https://github.com/Esri/solution.js/assets/2125181/8a5f637b-c65a-4892-bf21-cd85c6214a74)

![image](https://github.com/Esri/solution.js/assets/2125181/f6cf444a-da71-4ee0-acc0-e3e8666becc7)

**Comment by chris-fox** [comment]
@MikeTschudi, I am good with the current behavior that we only discover the dependencies of the story map if they are also shared in the group that is used to create the solution item. Thanks for confirming.

**Comment by chris-fox** [comment]
@MikeTschudi, I am curious how you handled de-templatizing back to an encoded url? Right now in the story map we are templatizing both the encoded and unencoded url with the same variable {{portalBaseUrl}}, how do you know during the de-templatizing whether the url needs to be encoded or not? Are we just doing it special for StoryMaps?

I was wondering if we should create a new variable like {{portalBaseUrlEncoded}} so it is explicit in the template and the logic can be applied to all item types.

**Comment by MikeTschudi** [comment]
@chris-fox, because StoryMaps have their own package, I made the changes only there.

When de-templatizing, I chose to look in the data section for the StoryMap for the pattern `portalUrl=https://`, which only appears in the encoded URLs (this is after the standard de-templatizing code has replaced `${portalUrl}` throughout).  These are replaced with the encoded version `portalUrl=https%3A%2F%2F`.

**Comment by chris-fox** [comment]
What do you think of making this more generic and apply to all item types via a unique variable? I am just wondering if we can handle the encoded portal url more broadly in case this comes up in other items as well.

**Comment by MikeTschudi** [comment]
Let's please wait until that situation arises so that we know what pattern(s) we need to match.

**Comment by chris-fox** [comment]
verified
