### ISSUE TITLE
Conditional Values dropped in deployed solution

### ISSUE THREAD

**Issue by ccheesemanTNC** [Esri/solution.js#1351]
I have a solution that uses conditional values.  My solution json is showing yes for all conditional values config settings but the outputted feature services no longer contain the conditional values.  I thought this was working but all of my deployments do not hold the values.

**Comment by chris-fox** [comment]
@ccheesemanTNC, could you provide some additional details on what you mean by conditional values in a feature service? Do you have a sample service I could take a look at that are failing to be maintained?

**Comment by ccheesemanTNC** [comment]
Thanks @chris-fox I have already repaired the broken services and was able to successfully redeploy a working solution with contingent values.  The only thing I can think of is an update that I did to symbology via Rest somehow corrupted the values.  I have no other explanation as to how it could have occurred.  I really thought I had lost my mind. :)
