### ISSUE TITLE
Add a parameter when deploying a solution to not create a solution item

### ISSUE THREAD

**Issue by chris-fox** [Esri/solution.js#1512]
This requirement came from the Field Maps team. They are providing an experience where users can create a new map from a map template. In their workflow they are always creating at most one web map and one or more feature layers. So they always take the user into the web map when it finishes deploying and don't have a need for the solution item. They would like a way to specify not to create a solution item when deploying a solution template.

When implemented, the result should continue to be creating a new folder with the solution's name, and all the items created as part of the deployment. However, no solution item should be created.

**Comment by MikeTschudi** [comment]
_Installed; available in version 5.8,0_

**Comment by chris-fox** [comment]
Works great
