### ISSUE TITLE
Add post-processing for item templates that still have variables after initial create

### ISSUE THREAD

**Issue by chris-fox** [Esri/solution.js#163]
In #47 we discussed adding a new property called circularDependency to help define a dependency to another item that shouldn't fall in the dependency tree or impact the order that items are created.

This was important for things like Workforce projects where the Project referenced a Group, but the Project was also shared with the Group. I am ok with doing a specific thing for workforce projects because it is a well known item type that will have an expected behavior.

We also wanted to use this situation for things like the R3 solution where one App's map referenced another App, and that App's map referenced the other app:

App1 > Map1 >App2
App2 > Map2 > App1

I originally proposed a json like this to capture this circularDependency but not impact the dependency tree:

[
  {"itemId": "App1"  ,"dependencies": ["Map1"]},
  {"itemId": "App2"  ,"dependencies": ["Map2"]},
  {"itemId": "Map1"  ,"dependencies": ["FS1"], “circularDependencies”: ["App2"]},
  {"itemId": "Map2"  ,"dependencies": ["FS1"], “circularDependencies”: ["App1"]},
  {"itemId": "FS1"  ,"dependencies": []}
]

What I am wondering if we could investigate instead is rather than listing this circular dependency explicitly in the template the map would have a variable reference to the other app. When the map is created during deployment the app variable isn't swapped out because the app hasn't been created yet and doesn't exist in the replacement dictionary. Then there would be some post-process after all items were created to check if variables still exist in any of the template items and if they are attempt to swap them out with the latest replacement dictionary and update the item.

This would allow us to support a large number of scenarios where items reference other templates but are not directly dependent on each other.

**Comment by shoe913** [comment]
Verified

**Comment by chris-fox** [comment]
This worked great in my tests @jmhauck, nice work.
