### ISSUE TITLE
Links on Solution Contents go to original items

### ISSUE THREAD

**Issue by shoe913** [Esri/solution.js#170]
After deployment, the links in the Solution Item's Contents section reference the original items, not the items deployed to my organization. 

I would expect these to link to my items, not the items in the deployment org.

**Comment by chris-fox** [comment]
@jmhauck, there also seems to be a regression here related to issue #101.  Now the entire template definition is written to the deployed solution rather than the simplified structure with just the item id, type and dependencies.

**Comment by shoe913** [comment]
Verified
