### ISSUE TITLE
Icons for non GIS Items do not match in solution contents

### ISSUE THREAD

**Issue by shoe913** [Esri/solution.js#176]
Icons for Word Documents and PDFs in the Solution Contents tree do not match the icons in the  contents section. 

![image](https://user-images.githubusercontent.com/11777080/73477675-8fa74880-4349-11ea-96e5-bdfcb83343e8.png)

**Comment by chris-fox** [comment]
Thanks Andy, This is something @jmhauck will have to look at in the item details logic for the Solution item.

**Comment by jmhauck** [comment]
Interesting. I had also noticed the other day that something was off around here as the icon for notebook doesn't show at all.

**Comment by shoe913** [comment]
Just to add a little more to this, it looks like the icon for a hosted table isn't coming through either. It just shows up as a hosted layer.

**Comment by shoe913** [comment]
Some more fun, Notebook icons should also be looked at.

**Comment by jmhauck** [comment]
@chris-fox @shoe913 I have a pull request submitted into the portal app that should resolve this.

**Comment by chris-fox** [comment]
@shoe913, because this requires a change to the item in the portal app, you will need to verify in devext. It will then push to production at 8.1.

**Comment by shoe913** [comment]
Verified.
