### ISSUE TITLE
Update logic for discovering Hosted Feature Service references in web map

### ISSUE THREAD

**Issue by chris-fox** [Esri/solution.js#178]
Currently in the web map for an operational layer the "itemId" property is optional. In addition, there is no assurances it accurately reflects the feature service referenced in the "url" property.

The "url" property is the most important property, it is required and will always correspond to the layer used in the web map. 

When authoring a solution we should use the url property to query the feature service and look for the "serviceItemId". If it has the property, it is a hosted feature service and that is the item id of the item associated with the hosted feature service. This is the item we should templatize.

If the operational layer doesn't have the "itemId" property we should add the property to the template for the layer and set it equal to the itemId variable so that when the web map is created in the users org the item id property is hooked up properly.

If it doesn't have this property it is not a hosted feature service and we should ignore it.

**Comment by shoe913** [comment]
Verified
