### ISSUE TITLE
Should users be allowed to deploy solutions they cannot use?

### ISSUE THREAD

**Issue by shoe913** [Esri/solution.js#181]
Using an account which does not have the essential apps bundle, I was able to deploy a QuickCapture project. 

I can see the value in this for an organization where publishers / data collectors are not the same people and their roles and duties do not overlap. 

Where I can foresee an issue is if the organization itself doesn't have the licensing to use an app such as Survey123, Workforce, or Collector. 

Does the deployment workflow check for license availability? or does it just copy the contents of the  solution item?

**Comment by chris-fox** [comment]
@shoe913, its a good question. I think at this point the only requirement will be that you are at least a creator with publisher permissions which is the minimum to create items and publish feature services.

**Comment by shoe913** [comment]
@chris-fox , thanks for the the clarification. I am still concerned about organizations without specific apps deploying solutions they can't use. I can already see someone deploying a solution and then calling tech support because it isn't working. 

Maybe this is something we can handle with the Solution Item Description. Since we will have full control over the items, maybe we simply add a disclaimer. 
![image](https://user-images.githubusercontent.com/11777080/73778599-52bfc500-4740-11ea-8fa0-beb7e7b08a45.png)

This would allow us to easily disseminate the use requirements, without preventing users from accessing solutions. 

(This may be a bit premature, not sure if we are thinking about these patterns yet)

**Comment by chris-fox** [comment]
@shoe913, we do plan to list these requirements in the Solution site documentation for the Solution that will likely be accessed from the learn more link in the item description. We are trying to reduce the amount of content we duplicate from the solution site help and the item description, but it is still TBD what we will be putting in the item description.

**Comment by shoe913** [comment]
@chris-fox , glad to know there is a plan in place to make sure everything is documented.
