### ISSUE TITLE
'All Capital Projects' Solution Item doesn't fully deploy. 

### ISSUE THREAD

**Issue by shoe913** [Esri/solution.js#186]
A few things going on here, not sure if they are symptoms or causes. 

1) The solution has 15 apps, the template only shows 10 in the contents
- Overall, there are 61 objects in the JSON to be copied

2) Only apps have been shared with the group used for the item. Maps are showing up in the contents

3) Deployment seems to work (all apps, layers, and maps are copied) but, deployment seems to hang at the very end and solution item cannot be accessed

**Comment by chris-fox** [comment]
@shoe913 Is this still an issue? If so we should add to the UC project.

**Comment by shoe913** [comment]
@chris-fox 

This seems to have cleared up. Will close it out
