### ISSUE TITLE
Thumbnails for deployed items are not copied 

### ISSUE THREAD

**Issue by shoe913** [Esri/solution.js#188]
When deploying solutions, the thumbnails for ArcGIS Pro Packages are not copied.

**Comment by shoe913** [comment]
This also occurs with Hosted Feature Layers and Hosted Feature Layer Views

**Comment by chris-fox** [comment]
I also have experienced this with other item types, but it is not consistently reproducible. Sometimes the thumbnails come over and sometimes not.

**Comment by shoe913** [comment]
Verified
