### ISSUE TITLE
Copy "properties" property into template and when deployed.

### ISSUE THREAD

**Issue by chris-fox** [Esri/solution.js#190]
We need to persist the "properties" property of the item when we author the template and write it to the deployed item.

We also need to copy the "properties" property from the Solution Item (Template) to the Solution Item (Deployed) in the user's organization.

**Comment by shoe913** [comment]
Verified

**Comment by chris-fox** [comment]
@MikeTschudi, @shoe913, I just attempted to copy a solution using the Copy Solution app and the properties weren't carried over to the result. Does this app just need an updated version of solution.js or is there something else missing?

http://ec2-18-219-57-96.us-east-2.compute.amazonaws.com/copySolutions/

**Comment by shoe913** [comment]
@chris-fox 

I tested this in the Deployment App and it worked fine. I just tested in the Copy App and I too see that it isn't snagging the properties. 

I did find that in order for the properties to even show up, I had to add them via code. For some reason, AGO Assistant didn't correctly save my changes.

**Comment by MikeTschudi** [comment]
The copySolutions example filters properties that it copies, and only copied the following properties:
* categories
* description
* documentation
* extent
* name
* snippet
* spatialReference
* tags
* title
* type
* typeKeywords

I've added
* licenseInfo
* properties
* thumbnail

@chris-fox, @shoe913, any more desired?

**Comment by chris-fox** [comment]
Thanks @MikeTschudi, could you also add

- culture
- accessInformation
- largeThumbnail

**Comment by chris-fox** [comment]
Verified
