### ISSUE TITLE
Handle Code Attachments for Web AppBuilder Applications

### ISSUE THREAD

**Issue by shoe913** [Esri/solution.js#194]
Maps which are not directly shared to the item are showing up in the contents. 

As I recall, this didn't happen last week. Is this an intended change or a bug?

![image](https://user-images.githubusercontent.com/11777080/74067126-599f3f80-49ad-11ea-9c08-568316a5441f.png)

**Comment by chris-fox** [comment]
@shoe913, could you check the template? I think that may be a code attachment which is associated with WAB apps.  If so, we don't want code attachments to be templatized with WAB apps, could you work with @MikeTschudi on this?

**Comment by shoe913** [comment]
@chris-fox @MikeTschudi 

Taking a closer look, this is a code attachment coming through as a map. This is probably related the the behavior I was seeing with #186 where incorrect items where showing up. 

I tried removing the code attachment from the app used to create the Solution Template and this seems to correct the extra dependency. It also looks like ArcGIS Online is automatically rebuilding the code attachment for us afterwards. 

Couldn't find an existing issue for code attachments, so I'll turn this into one. 

I think if we ignore the code attachment so it doesn't copy this could address the issue.

**Comment by shoe913** [comment]
@MikeTschudi 

From testing, it looks like displaying the code attachment may be a regression. Currently, we recreate the code attachment if it is missing from the item, which is a behavior we'd like to keep. 

On a related note, I noticed this morning that apps with missing code attachments do not show up in the Solution Item. Not sure what changed, but it was not doing this last week, so I suspect it is a different regression. 

- Keep / create code attachment
- Prevent code attachment from showing on the Solution Item 
- Show app in Solution Item if code attachment is missing

**Comment by MikeTschudi** [comment]
@shoe913, the code attachment branch is not yet merged into the develop branch, so you won't see the changes yet

**Comment by chris-fox** [comment]
Added to UC project, lets make sure we get this addressed soon after dev summit.

**Comment by MikeTschudi** [comment]
With eacbc6994ae52f45d977845d3c9848f29c38eeab, removed reference from WMA to Code Attachment in Solution template and added retries to updating a WMA's URL

**Comment by shoe913** [comment]
Verified
