### ISSUE TITLE
Vision Zero does not deploy: Unimplemented Item type error

### ISSUE THREAD

**Issue by shoe913** [Esri/solution.js#201]
When trying to deploy Vision Zero Solution Item, deployment hangs at 89.89%

Errors in console suggest hang may be due to a specific layer. JSON of solution Item also has an 'unknown' item type. 

![image](https://user-images.githubusercontent.com/11777080/74290820-d69d2280-4ce7-11ea-8546-697d3c576a64.png)

From what I can tell, the issue is with this layer: https://services7.arcgis.com/piPfTFmrV9d1DIvN/arcgis/rest/services/TrafficCrashes_public/FeatureServer

This is owned by the LocalGovDeployment Alias (same as other items in solution) and is publicly available.

**Comment by chris-fox** [comment]
@shoe913, I think this is related to #178. I am guessing the Web Map has an operational layer with an ItemID property that is pointing to an item id that no longer exists. My guess is when @jmhauck resolves #178, that when you re-author the Vision Zero solution the reference in the web map will be right and you will no longer have this unknown type.

**Comment by chris-fox** [comment]
Also I saw this same issue in Election Management in the Dashboard for one of the web maps, I actually resolved the itemID reference in the web map because I wanted to demo it today, but it will be easy to test this case by putting a bad item id into a web map.

**Comment by shoe913** [comment]
Looks to have been fixed in #178
