### ISSUE TITLE
Should Solution Items have Metadata?

### ISSUE THREAD

**Issue by shoe913** [Esri/solution.js#202]
Related to #121 

When creating a solution template, we have the option to create Metadata for the template. This is not an option for the deployed template. 

I'm not currently aware of any metadata standards we are following for solutions in general and given that we're not storing any pertinent information for deployment in the metadata, I wonder if we even need it.

**Comment by chris-fox** [comment]
@shoe913, are you referring to the Metadata button in the item details? I see this in both templates and deployed solutions. I think this is just default ability on all item types. I am fine with leaving it, doesn't hurt if people want to add metadata for their solution item.

**Comment by shoe913** [comment]
@chris-fox 

Yeah, that is the button I was referring to. I didn't see it on the deployed solution item at the time, it looks like it is there now. 

I've thought about this quite a bit more and I think we may want to encourage internal users to create some basic metadata for our solution items. Bare minimum: the release date and a versioning scheme. 

This would help us identify where potential issues may be when we release to Enterprise. We'll know enterprise has version 'x.x' which has issue 'abc'. Additionally, this could help other internal stake holders (especially with scripting bugs) because we could easily identify where issues are  introduced and fixed. 

I think this would be more reliable than the "when did you deploy?" question since issues don't always crop up conveniently. It could be quite a bit of time between deployment and configuration, or just deployment and issue. 

Since all solution items would be brand new, we can create a versioning system for the item itself. Package components of the items (ICAP, Crime Analysis, Adopt-A, etc.) could still follow their own patterns without us needing to redo anything. We could know "Adopt-A Catch Basin 3.0 has Adopt-A-Catch Basin project 1.0".

**Comment by chris-fox** [comment]
I think as a property of an item we should include it, if we don't use it no big deal, but if we want to in the future it will be nice to have.
