### ISSUE TITLE
Proposed New Property handling: "deployJobId" on incoming/outgoing JSON from deployer.deploySolution

### ISSUE THREAD

**Issue by cosbyr** [Esri/solution.js#205]
I would like to be able to pass an additional property to the deployer.deploySolution function
deployer.deploySolution(itemInfo.id, **itemInfo.deployJobId**, userSession, options)

Returned JSON on successful deployment or unsuccessful deployment would bring back the same deployJobId property. The Id would be a unique string that i'll generate.

I think this will be the most dependent way to determine which card/cards behavior/state I need to change based on feedback from deployer.deploySolution.

This will help tackle the scenario (although rare) where a user might decide to deploy the same solution more than once concurrently.

**Comment by MikeTschudi** [comment]
Implemented via PR #241
