### ISSUE TITLE
Create ID and Version Number during Solution Template Creation

### ISSUE THREAD

**Issue by shoe913** [Esri/solution.js#226]
Version number should pre-populate to 1.0 when template is created, the ID should be a guid with no hyphens. 

    "properties": {
        "version": "1.0",
        "id": "b00190d537784a80a2e7472e7e4272f9"
    },

This will be to help support versioning of solutions templates.

**Comment by chris-fox** [comment]
@shoe913, @MikeTschudi, I was just thinking I would like to add an additional thing to this request:

if the group has the tags deploy.id.XXXXX or deploy.version.XXXXXX, we should use the values specified in the tags in the resulting solution. 

For example I have a solution with the tags:

deploy.id.b00190d537784a80a2e7472e7e4272f9 and deploy.version.1.2

This should result in a the properties specified as:

    "properties": {
        "version": "1.2",
        "id": "b00190d537784a80a2e7472e7e4272f9"
    }

If one or both isn't specified we should use the logic described in the original comment to generate either the id or version.

This will allow the solution author to control this for version updates of their solution.

Finally, if a user does specify these tags in the group could we remove these tags from the resulting solution item? I would also like to remove the deploy.solution or deploy.solutions tags from the resulting item. These tags are only used to control the creation of the solution and are not needed in the resulting solution item.

**Comment by MikeTschudi** [comment]
@chris-fox, I don't quite understand this.  Does this summarize the first part:
* if group has deploy.id.XXXXX, use it for created solution item's deploy.id; owse, generate guid
* if group has deploy.version.XXXXX, use it for created solution item's deploy.version; owse, use 1.0

Do you want to rename `deploy.commonid` to `deploy.id`?

Would you please clarify the last paragraph?  It sounds as if we're removing tags from the created solution item that are needed to find it and to check its version, contravening the rules above.

**Comment by chris-fox** [comment]
@MikeTschudi First part is correct. I want to use 'deploy.id'. Since the property name is consistent with what we are storing in the item properties.

In regards to the last paragraph. We don't need the deploy.solution, deploy.id, or deploy.version tags on the resulting Solution item to discover the solution or check its version.

We are using the properties on the item to discover a Solution's id and version. We are also using the typeKeyword 'template" to know if a Solution can be deployed.

So we should remove these tags from the resulting item to create a better end user experience and reserve tags just for searching for Solutions that match a specific search criteria in the app.

**Comment by MikeTschudi** [comment]
@chris-fox, then

* if group has **tag** deploy.id.XXXXX, use its value for created solution item's **properties.id**; owse, generate guid for created solution item's **properties.id**

* if group has **tag** deploy.version.XXXXX, use its value for created solution item's **properties.version**; owse, use `1.0` for created solution item's **properties.version**

* groups tags are copied into created solution item, **except for any tag prefixed with `deploy.`**

?

**Comment by chris-fox** [comment]
@MikeTschudi, perfect

**Comment by MikeTschudi** [comment]
@chris-fox, merci!

**Comment by shoe913** [comment]
Verified
