### ISSUE TITLE
Update the Create Solution and Copy Solution apps to only look for groups/items owned by the logged in user.

### ISSUE THREAD

**Issue by chris-fox** [Esri/solution.js#227]
Once we open this up to all of the Solutions teams we will start to see a lot of groups and items in these apps and it makes it difficult to find the thing we are looking for. Particularly as an admin in the org you currently see everything.

To reduce the clutter and allow you to focus in on the items you are working on I would like to only show the groups I own in the Create Solution app and the items I own in the Copy Solution app. As an admin if I need to do something with a group or item owned by someone else I can always transfer ownership.

**Comment by chris-fox** [comment]
FYI.. @shoe913

**Comment by MikeTschudi** [comment]
@chris-fox, public and private content that you own, correct?

**Comment by chris-fox** [comment]
@MikeTschudi, correct, private, shared with org, or public. Any content you own.

**Comment by chris-fox** [comment]
Verified
