### ISSUE TITLE
Support concurrent deploys of solutions using folders of the same name

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/solution.js#243]
Early folder creation involved trying a name; if it failed, append or increment a digit at the end of the name and try again. This is repeated until a name succeeded.

A subsequent enhancement reduced server round trips from *n* to two by querying for all folders, and then using those results to create a unique name.

Since deployment by default uses the solution name for the deployed folder name, the improved method does not support concurrent deploys of solutions with the same name: each deploy has basically the same list of existing folders, but as soon as one deployment creates a unique name based on that list, all others will have obsolete folder lists and will fail when trying to use that same no-longer-unique name.

If we will support concurrent deploys, then we need to revisit folder creation. We could
* return to the original multiple-trip test method
* append a timestamp to the folder name
* append a pseudorandom string (e.g., the 8-character key that we generate for Hub) to the folder name

None of these methods needs the call for the list of folders. The second two should have a failure fallback to try again with new values. (Basically the same as the first, but likely to be rarely used, so we're still looking at about one server roundtrip.)

@chris-fox, will we support concurrent deploys? If not, then apps need to block them. (I don't think that the solution.js library can do the blocking.)

**Comment by jmhauck** [comment]
@MikeTschudi wouldn't we still check the current folder list regardless. If we could see that the first name or two we would try are definately taken no need to fail on them.

**Comment by MikeTschudi** [comment]
@jmhauck, I think that you're right for the first method--we'd get a head start on names by skipping iterations that are known to exist.

For the other two methods, I'm guessing that collisions with millisecond-level timestamps and pseudorandom ids would be really rare.

**Comment by chris-fox** [comment]
I like the first approach and as @jmhauck suggests still fetch all the folders so you don't need to fail on the known ones, you would only fail/retry in the situations where a folder has been added since you requested the folders.
