### ISSUE TITLE
Add searchGroupItems to arcgis-rest-js

### ISSUE THREAD

**Issue by cosbyr** [Esri/solution.js#245]
The requirement to put our Solution Template Items into a group and use categories at the group category level requires a new function be added to the arcgis-rest-js library

@MikeTschudi 
See related issue here: https://github.com/Esri/arcgis-rest-js/issues/658

Requirements:
- Follow the pattern in [portal.searchItem](https://esri.github.io/arcgis-rest-js/api/portal/searchItems/) which is built on the [Search](https://developers.arcgis.com/rest/users-groups-and-items/group-content-search.htm) REST query to create a similar query called `portal.searchGroupItems` which is built on the [Group Content Search](https://developers.arcgis.com/rest/users-groups-and-items/group-content-search.htm) REST query.

For the most part it appears that the queries are almost identical one just needs to point to a different endpoint.

- Create a wrapper of this query in the viewer or deployer package in this repo that does built-in HTML sanitization

**Comment by MikeTschudi** [comment]
Category search requires fix in [arcgis-rest-js](https://github.com/Esri/arcgis-rest-js/issues/685)

**Comment by chris-fox** [comment]
Verified
