### ISSUE TITLE
Support Cache Control property on Feature Services and Views

### ISSUE THREAD

**Issue by chris-fox** [Esri/solution.js#246]
For non-editable Feature Services and Views you can set the Cache Control property to specify the maximum time users can wait before seeing an updated. This improves performance and scalability for apps if the data doesn't update frequently: 

![image](https://user-images.githubusercontent.com/6796763/76966315-28932280-68fc-11ea-91d9-a4cded0a3d6a.png)

This setting is only visible from the admin end point, we are currently not persisting it in the template and as a result the new layer is being created with the default setting of 30 seconds. Since we are not requesting the admin end point from any service we should be able to get this property and persist it in the template.

**Comment by shoe913** [comment]
Verified
