### ISSUE TITLE
Solution Item Thumbnails blurry after deployment

### ISSUE THREAD

**Issue by shoe913** [Esri/solution.js#250]
After deploying or copying solutions, thumbnails become blurry. 

Looks like the thumbnail is being stored as both the resized version and the original. The resized version is then being used by the item. 

Resized by AGOL:
https://www.arcgis.com/sharing/rest/content/items/b637babcf38244b9b9718ee3887ac535/info/thumbnail/thumbnail1584552189370.jpeg 

Original:
https://www.arcgis.com/sharing/rest/content/items/b637babcf38244b9b9718ee3887ac535/info/thumbnail/thumbnail1584552189370_orig.jpeg

**Comment by chris-fox** [comment]
@shoe913, @MikeTschudi, I don't know the rules with thumbnails that well. I am not sure how consistent the _org thumbnail is. If this seems risky to try to persist the original thumbnail I think we may be able to workaround this in the app.

**Comment by chris-fox** [comment]
Adding @cosbyr 

I see ArcGIS Online often uses the following param when fetching the thumbnail:

https://<item-url>/info/thumbnail/thumbnail.png?w=400
https://developers.arcgis.com/rest/users-groups-and-items/common-parameters.htm

Currently in the app we are using _orig? It seems it would be safer to use this param instead and potentially better performance?

This is what I am seeing. When I upload a 600x400 thumbnail, online creates a 200x133 thumbnail and stores it as its default:

https://www.arcgis.com/sharing/rest/content/items/b637babcf38244b9b9718ee3887ac535/info/thumbnail/thumbnail1584552189370.jpeg

It stores the original with the same name _orig:

https://www.arcgis.com/sharing/rest/content/items/b637babcf38244b9b9718ee3887ac535/info/thumbnail/thumbnail1584552189370_orig.jpeg

You can then request a larger size using the param:
https://www.arcgis.com/sharing/rest/content/items/b637babcf38244b9b9718ee3887ac535/info/thumbnail/thumbnail1584552189370.jpeg?w=400

But if you request a size bigger than is available it returns the highest size it has:

https://www.arcgis.com/sharing/rest/content/items/b637babcf38244b9b9718ee3887ac535/info/thumbnail/thumbnail1584552189370.jpeg?w=800

So during the template creation process so we be requesting larger size thumbnails and persisting that in the template? In addition, should we be doing the same for the solution item itself?

**Comment by MikeTschudi** [comment]
When a deployed Solution is created, its spec includes the URL to the Solution Template's thumbnail, but the URL is missing the w=400 parameter.

Thanks to @cosbyr for catch

**Comment by chris-fox** [comment]
Verified
