### ISSUE TITLE
Create service under user folder initially to remove the need to move it.

### ISSUE THREAD

**Issue by chris-fox** [Esri/solution.js#257]
I notice for all services and views we are creating the service in the users home folder and then moving it to the appropriate folder. This requires 2 requests for each services/view.

https://www.arcgis.com/sharing/rest/content/users/chri4849_lg/createService

We could streamline this by creating the service/view directly in the folder to start with, by adding the folder id to the request url.

https://www.arcgis.com/sharing/rest/content/users/chri4849_lg/8b3c636d6727407ba63ab172468e8f04/createService

**Comment by MikeTschudi** [comment]
Works like a charm. The create + move behavior is in arcgis-rest-js package `arcgis-rest-service-admin`;  PR [Supply folder parameter during creation so that a subsequent move is not needed #689](https://github.com/Esri/arcgis-rest-js/pull/689).

**Comment by MikeTschudi** [comment]
Finally merged into arcgis-rest-js; will get with next release

**Comment by chris-fox** [comment]
Verified on QA
