### ISSUE TITLE
Cross-browser support

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/solution.js#258]
Support for
* Chrome
* Firefox
* New Microsoft Edge (versions > 80)
* Safari

Partial support for Legacy Microsoft Edge (versions &ge; 41.16299 and &le; 44.18362; EdgeHTML/[Can I Use](https://caniuse.com/) versions 16 -18.)  [Edge versions](https://en.wikipedia.org/wiki/Microsoft_Edge)

**Comment by chris-fox** [comment]
Seems like we should not worry about IE11 support, seems to be the direction the rest of the apps are going as well.

**Comment by chris-fox** [comment]
@MikeTschudi, I was having issues with the Coronavirus Response application failing in Edge, then I installed the 'new Edge' and was able to deploy successfully. I didn't even know about the 'new Edge' so doing some more research to see what we need to consider for support with the 'legacy Edge'

https://support.microsoft.com/en-nz/help/4026494/microsoft-edge-difference-between-legacy

**Comment by MikeTschudi** [comment]
Added File constructor polyfill (01b5c8be3153d008bc4a3944f0faa328dc32f497)

**Comment by MikeTschudi** [comment]
In version 0.8.6

**Comment by chris-fox** [comment]
Verified.
