### ISSUE TITLE
Review replacing clear text platform cookie (esri_auth) with encrypted platform cookie 

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/solution.js#303]
From AGO team:

> All,
> 
> We are making some improvements in how we create and maintain OAuth cookies when ours users sign in.  For security reasons, we want to move away from a clear text cookie that can be manipulated by clients to an encrypted cookie that is set by the platform and can be used only by the platform.
> 
> Please fill out a survey to help us understand how your app depends on the esri_auth cookie.  This is the clear text platform cookie that is bound to .arcgis.com domain.  See illustration under this email for more info.
> 
> To fill out this survey:
> •	Open OAuth Cookie Survey.xlsx
> •	Add a column with your product/app name and answer questions in each row. 
> •	Even if your app doesn’t use the esri_auth cookie, please add a column with your product name and add N/A so that we know that is the case
> •	Please fill this survey by Friday, May 8th.
> 
> We are planning to remove our reliance on the clear text esri_auth cookie in phases:
> 1.	8.1 (March 2020)
> a.	Set both the clear text cookie (esri_auth) and the encrypted cookie (esri_apoc) – Done 
> 2.	8.2 (June 2020): 
> a.	Update JS API to account for encrypted cookie. 
> b.	Survey app teams for how they use the clear text cookie (this email) 
> c.	Provide documentation to app teams on how they can stop relying on the clear text esri_auth cookie
> 3.	June 2020 onwards
> a.	Apps to start implementing recommendations to avoid use of clear text esri_auth cookie
> b.	Apps to certify that they do not need the clear text cookie any more
> 4.	Once all apps have certified that they do not need the clear text cookie
> a.	Stop setting esri_auth cookie on DEVEXT early in the release.  The exact release will depend on 3b.  We are shooting for the September release, with the December release as a fallback.
> b.	App teams to certify again that apps work fine without the clear text cookie
> 
> Please note that we will be mindful of not breaking any apps when we complete the switch to the encrypted cookie.  Your participation in this process is critical in helping us make sure that we do not break app workflows.
> 
> Thanks,
> 
> Mehul & Sentha

**Comment by MikeTschudi** [comment]
Completed

**Comment by slibby** [comment]
@MikeTschudi  I came across this from a Google search and as this is an Esri internal email thread on a public Github repository, I would suggest editing the issue to remove the original notification.

**Comment by MikeTschudi** [comment]
Thank you very much, @slibby
