### ISSUE TITLE
Ignore default extents when creating items if extents are invalid

### ISSUE THREAD

**Issue by shoe913** [Esri/solution.js#313]
When an organization has an invalid default map extent, the solution.js will not create the solution items correct and fail. 

When the code encounters this, we should handle for for the error and default the extent of the full base map.

![image](https://user-images.githubusercontent.com/11777080/81100940-30198580-8ec2-11ea-9a95-3bd41a09e666.png)

**Comment by chris-fox** [comment]
Verified.
