### ISSUE TITLE
Update creation of version and id tags to use typeKeywords rather than properties.

### ISSUE THREAD

**Issue by chris-fox** [Esri/solution.js#319]
To support reporting we need to move our solution id and version from the properties to the typeKeywords of the item. So we will be looking for the following typeKeywords:

"solutionid-XXXXXSomeGuidXXXXXXX"
"solutionversion-1.0"

We originally did this work in #226, I would like to keep the same behavior as we implemented in this issue but rather than writing these to the properties of the item, we write these as typeKeywords following the format above.

**Comment by shoe913** [comment]
Verified
