### ISSUE TITLE
Deployment does not correctly unpack special characters

### ISSUE THREAD

**Issue by shoe913** [Esri/solution.js#321]
When creating and deploying a solution, special characters around svg elements are not consistently converted to/from HTML. 

In example below, characters (for example  < and > ) are getting parsed by the dashboard instead of the deployment app. This prevents the icons from showing correctly.

![image](https://user-images.githubusercontent.com/11777080/81454898-5fd6c080-9142-11ea-8973-68cf4a541ff9.png)

![image](https://user-images.githubusercontent.com/11777080/81455087-f5725000-9142-11ea-8135-e2993ddfcad6.png)

**Comment by MikeTschudi** [comment]
Solutions with html--including svgs--embedded in their data section will need to be rebuilt because the security scan before the work associated with this issue disables the html.

**Comment by shoe913** [comment]
Verified
