### ISSUE TITLE
Add Workforce Project type

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/solution.js#33]
@chris-fox:
> Workforce Projects are a json item with standard references to 2 web maps, 4 feature services and a group.

> You can find a good example of a Workforce Project in the http://arcgis4localgov2.maps.arcgis.com/ org with the item id e4f57a8460b14b46a54e4519325f5ded.

**Comment by jmhauck** [comment]
This is dependent on #47

**Comment by shoe913** [comment]
Verified, workforce projects deploy.
