### ISSUE TITLE
Copy App does not copy all resources 

### ISSUE THREAD

**Issue by shoe913** [Esri/solution.js#330]
This Solution Item contains 3 surveys (saved as zips) and 3 info.json files stored in the resources. 
https://localdeployment.maps.arcgis.com/home/item.html?id=e6fede9309a540b0b231cae13e0c67e7

After being copied to devext, all three survey zips are missing and one info.json file is missing from the resources.

When the 'broken' item is deployed in devext, everything appears to be working correctly despite the resources not being present.

**Comment by MikeTschudi** [comment]
AGO is accepting each resource and returning HTTP 200 responses such as `{"success":true,"itemId":"af830084316e4379a444acd0243dfc4a","owner":"myaccount","folder":null}`

Of 15 addResources calls with `success` responses, only 9 actually ended up in item. addResources says that [A maximum of 50 files can be added each request. Each file should be no more than 50 Mb.](https://developers.arcgis.com/rest/users-groups-and-items/add-resources.htm), so it appears that we will need to bundle resources into single calls to AGO.

**Comment by shoe913** [comment]
Verified
