### ISSUE TITLE
Incorrect unpkg URLs in doc

### ISSUE THREAD

**Issue by mpayson** [Esri/solution.js#335]
Looks like the unpkg, non-SRI URLs in the doc add an extra `@esri/solution-` to the path?

For [`creator`](https://esri.github.io/solution.js/api/creator/)
doc: https://unpkg.com/@esri/solution-creator@0.9.1/dist/umd/@esri/solution-creator.umd.min.js
actual: https://unpkg.com/@esri/solution-creator@0.9.1/dist/umd/creator.umd.min.js

**Comment by MikeTschudi** [comment]
Thanks, @mpayson; fix will go out with next point release of project

**Comment by MikeTschudi** [comment]
Done, but needs solution.js build > 0.10.0

**Comment by shoe913** [comment]
Verified
