### ISSUE TITLE
Carry over editing settings/capabilities from Feature Service (and View) template

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/solution.js#34]
@chris-fox:
> In the Manage Right of Way Activities solution there are several views that have different editor settings depending on the use case/user who would work with them. Some are intended for the public and should have editing disabled, some are internal and should allow users to add records, and some may have full editing permission. We need to carry these settings over when the solution is deployed.

**Comment by chris-fox** [comment]
@jmhauck can confirm if this was included in his feature service work

**Comment by jmhauck** [comment]
@chris-fox yes...for example with this solution we have the source feature service:

**ROWPermits**
-	ROW Permits (feature service)
	Source and deployed have: "capabilities" : "Create,Query,Update,Editing,Extract"
-	ROW Permit Comment (feature service)
	Source and deployed have: "capabilities" : "Create,Query,Update,Editing,Extract"

The views:

 **ROWPermits_manager**
-	ROW Permits (view)
	Source and deployed have: "capabilities" : "Create,Delete,Query,Update,Editing"
-	ROW Permit Comment (view)
	Source and deployed have: "capabilities" : "Create,Delete,Query,Update,Editing"

**ROWPermits_publiccomment**
-	ROW Permits (view)
	Source and deployed have: "capabilities" : "Create,Query,Editing" 
-	ROW Permit Comment (view)
	Source and deployed have: "capabilities" : "Create,Query,Editing"

**ROWPermits_dashboard**
-	ROW Permits (view)
	Source and deployed have: "capabilities" : "Query"
-	ROW Permit Comment (view)
	Source and deployed have: "capabilities" : "Query"

**ROWPermits_review**
-	ROW Permits (view)
	Source and deployed have: "capabilities" : "Create,Query,Editing"
-	ROW Permit Comment (view)
	Source and deployed have: "capabilities" : "Create,Query,Editing"

**ROWPermits_locator**
-	ROW Permits (view)
	Source and deployed have: "capabilities" : "Query"
-	ROW Permit Comment (view)
	Source and deployed have: "capabilities" : "Query"

**Comment by chris-fox** [comment]
Verified
