### ISSUE TITLE
Failure to deploy when feature services aren't unique

### ISSUE THREAD

**Issue by shoe913** [Esri/solution.js#342]
Fringe case.

When deploying a solution, if multiple feature exist with the same prefix and a guid, the solution will fail to deploy because each feature is given the same name during deployment.

Ex.
Service A:
service_GUIDA -> service_newGUID

Service B:
service_GUIDB - > service_newGUID

Workaround:
Change Item definition in solution so the names are different.

**Comment by chris-fox** [comment]
This will happen with multiple surveys authored where the app creates the service, or with multiple workforce projects in the solution.

**Comment by jmhauck** [comment]
@chris-fox the first occurance will get the GUID as it does today. Any additional occurances will get an additional "_" with a number. For example:

Service A:
service_GUIDA -> service_newGUID

Service B:
service_GUIDB - > service_newGUID_1

Service C:
service_GUIDC - > service_newGUID_2

**Comment by chris-fox** [comment]
@jmhauck, makes sense thanks.

**Comment by jmhauck** [comment]
[fs-names](https://github.com/Esri/solution.js/tree/b/fs-names)

**Comment by shoe913** [comment]
Verified
