### ISSUE TITLE
Quick Capture Project issue with adding resources

### ISSUE THREAD

**Issue by shoe913** [Esri/solution.js#346]
When deploying a quick capture project, it will fail with the following error. 

![image](https://user-images.githubusercontent.com/11777080/82946787-d6056080-9f53-11ea-8eda-5d5e1b24c8d3.png)

The resource causing the failure is the qc.project.json. This does exist and is accessible (verified by python api). 

It appears the UpdateResources request doesn't have the correct path for the json file for the package. In the post no sub folder for storing resources is listed

![image](https://user-images.githubusercontent.com/11777080/82946734-bff7a000-9f53-11ea-9c16-330153ab4914.png)

**Comment by shoe913** [comment]
Can reproduce with "Andy Quick Capture"

**Comment by chris-fox** [comment]
Assigned to @jmhauck because he originally did the work

**Comment by shoe913** [comment]
Verified
