### ISSUE TITLE
Store feature service default extent in template in case org extent isn't valid for service spatial reference

### ISSUE THREAD

**Issue by chris-fox** [Esri/solution.js#348]
In some cases a service may have a local coordinate system but the org extent it is being deployed to has a world wide extent. When we attempt to project to the org extents some of the extent values are returned as NaN. This causes a failure when attempting to create the service.

To resolve this during templatization I would like to store the Services "initialExtent" property as a new "defaultExtent" property in the properties object of the template like below (If the service doesn't have an "initialExtent" property, try to use its "fullExtent" property).

Then during deployment if we attempt to project the org extents into the extent of the spatial reference of the service and it comes back with any NaN values we should use this defaultExtent property instead.

"properties": {
	"service" : {...},
	"layers" : [...],
	"tables" : [...].
	"defaultExtent" : {
		"xmin" : -9838082.6378369723, 
		"ymin" : 5117637.3534149043, 
		"xmax" : -9779417.2661889177, 
		"ymax" : 5137490.5407675551, 
		"spatialReference" : {
		  "wkid" : 102100, 
		  "latestWkid" : 3857
		}
	  }
	}

**Comment by jmhauck** [comment]
[f/store-fs-extent](https://github.com/Esri/solution.js/tree/f/store-fs-extent)

**Comment by shoe913** [comment]
Verified
