### ISSUE TITLE
Feature Service Naming Convention

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/solution.js#35]
@chris-fox:
> Following the pattern in other apps (Survey123, Workforce) when we deploy a Solution we should first create the Solution item, from this we will get the item id of the Solution. This item id then should be added at the end of the feature service name to ensure it is unique in the organization:

> ROWPermits_299c12aa9ba442418079603f5c39f8c3
ROWPermits_dashboard_299c12aa9ba442418079603f5c39f8c3
ROWPermits_locator_299c12aa9ba442418079603f5c39f8c3

> After the service is created we should update the title of the item to match that of the original item defined in the template:

> ROWPermits
ROWPermits_dashboard
ROWPermits_locator

> The name will be used in the url of the service, but this is really the only place the user would see this quid, everywhere else they would see the nice item title.

> If a service already has an item id quid in the name as defined in the template, we should swap it out for the new item id of the Solution.

**Comment by chris-fox** [comment]
Verified
