### ISSUE TITLE
Folder Naming Convention

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/solution.js#36]
@chris-fox:
> When creating a new folder with a deployment we should default the folder name to be the same as the Solution, i.e 'Manage Right of Way Activities'. If that folder already exists we should add a 1, 2, 3, etc. continuing to increment with each instance.

> Manage Right of Way Activities
Manage Right of Way Activities 1
Manage Right of Way Activities 2

**Comment by MikeTschudi** [comment]
@chris-fox, if deployment org contains folders
> Manage Right of Way Activities
Manage Right of Way Activities 2

this implementation will create folder "Manage Right of Way Activities 1", the first available name in the series.

**Comment by chris-fox** [comment]
Verified
