### ISSUE TITLE
Item id of dependency in deployed Solution item is not being updated during creation

### ISSUE THREAD

**Issue by chris-fox** [Esri/solution.js#361]
I noticed today there is an issue in Production with the solution contents, nothing is showing as nested, it is showing as one long list. It appears the dependency item id is not being replaced with the new item, it continues to point to the original item that was templated.

Here is an item I can repro with, the original template looks fine, the resulting deployed solution has the issue.

https://localdeployment.maps.arcgis.com/home/item.html?id=f0af9a3c0e494229ac37a4539441ad26

**Comment by shoe913** [comment]
Verified
