### ISSUE TITLE
Survey123 item descriptions with code prevent web survey from functioning

### ISSUE THREAD

**Issue by shoe913** [Esri/solution.js#367]
When a Solution Item contains a Survey123 Survey whose description contains code (see item below for example) the deployed survey cannot be accessed on the web. 

https://localdeployment.maps.arcgis.com/home/item.html?id=75ac397de9f149b1aede0bc2b23c7563

**Comment by dbouwman** [comment]
@shoe913 can you make this item public? or - can @rweber-esri and I get accounts in whatever org you are working in so we can 👀 this?

Thanks!

**Comment by shoe913** [comment]
@dbouwman @rweber-esri 

Item is now public. Thanks!

**Comment by chris-fox** [comment]
@shoe913, not sure if I missed a step, but i tried to deploy it and it worked fine and was able to access the survey on the web. I used the latest version of our ec2 app to do this.

**Comment by rweber-esri** [comment]
> @shoe913, not sure if I missed a step, but i tried to deploy it and it worked fine and was able to access the survey on the web. I used the latest version of our ec2 app to do this.

I'm observing the same; deployment completes successfully & I'm able to access the survey editor as well as submit & view results. @shoe913 are you still able to reproduce?

**Comment by shoe913** [comment]
@chris-fox @rweber-esri 

It seems to be working for me now as well. Not sure what happened, since On Friday this was 100% reproducible. 

I'll close the issue for now and keep and eye on it.
