### ISSUE TITLE
Add support for Native Application items as fileProcessor type

### ISSUE THREAD

**Issue by chris-fox** [Esri/solution.js#368]
This item type data is just a zip so assuming it will be pretty straightforward. It is for app studio applications. The team is planning to release a solution that has this item type after UC so want to see if we can get it in 8.2.

https://www.arcgis.com/home/item.html?id=a6f18f73a0d244a28fa38573d804168b

@jmhauck, let me know if you see any risk with putting this in now.

**Comment by shoe913** [comment]
Verified
