### ISSUE TITLE
Deployed ArcGIS Pro Packages Cannot be Opened Directly from AGOL

### ISSUE THREAD

**Issue by shoe913** [Esri/solution.js#369]
1) Deploy a solution with and ArcGIS Pro Package (Recreation Outreach or Sewer Data Management)
2) Navigate to package's Item Details Page
3) Click "Open in ArcGIS Pro"

BUG: ArcGIS Pro will launch, but the item will not download and open the package. 

If you click download, and then open the ppkx, everything works correctly. This seems to be an issue with how the pitemx is referencing the package.

**Comment by chris-fox** [comment]
@shoe913, did you find a workaround for this? If not, seems like it should be critical for the June release.

**Comment by shoe913** [comment]
@chris-fox 

There are 2 workarounds which can be used. 

1) Download the package instead of clicking "Open In ArcGIS Pro". I think this will be what most people do if the open button doesn't work the first time. 
2) We ship the project as a zip. This would force people to download. 

I'll bump priority and we can make the work arounds be a last resort. If we can't get this addressed.

**Comment by chris-fox** [comment]
@shoe913, this worked for me. At first it didn't work, but the problem for me was that I wasn't signed into the org in Pro that I had deployed to and the item was private, so it couldn't reach the item to download and extract. After I signed into the portal in Pro, closed Pro and then tried the Open in Pro it worked fine. I am at 2.6 Beta. Could this be the same issue for you?

We don't create or clone the pitemx file, this is generated dynamically by the item so I am not sure how we could cause an issue here.

**Comment by shoe913** [comment]
@chris-fox 

At first I would see the issue regardless of the org I was signed into. 

I cracked open the pitemx file and noticed that one of the item id's being referenced was the original item from the org used to create the solution item. I changed this to match the new item id and everything then worked fine. 

As a test, I then changed the item id back to the original value (from source org, not target), and now the item will open correctly if logged into the target org. 

I'm on a daily build of 2.6, so that could be the issue. However, other folks are seeing this behavior with 2.5. I've asked to re-verify what org they are signed into when clicking "Open in ArcGIS Pro"

**Comment by chris-fox** [comment]
If you could get an item that produces the pitemx pointing back to the original item id I would be interested in checking it out because we aren't include it as a resource with the item, so would be good to figure out why it continues to point to it.

**Comment by chris-fox** [comment]
@shoe913, tested this on QA today with Transit Outreach and the pro project worked both ways (Opening from Pro, or Opening from item details). This is the last issue in Solution.js. Wondering if we can close and wait to see if we get any other reports of an issue?
