### ISSUE TITLE
Add Hosted Feature Layer Views type

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/solution.js#37]
@chris-fox:
> In the Manage Right of Way Activities, there are several views of the ROWPermits feature service (ROWPermits_dashboard, ROWPermits_manager, etc.). When authoring the Solution the feature service should be seen as a dependency of the view and the when deployed the views should be recreated from the new ROWPermits layer.

> The ROWPermits solution has a series of 'simple' views where a view is constructed from a single source. Hosted feature layer views can also be created from a join and we also need to support these types of views. The Citizen Problem Reporter Dashboard uses a joined view and can be used to test this process.

> CitizenProblems_surveyresults
CitizenProblems

> To reconstruct these views you will need access to the admin info of the service, so we should store this information when authoring the solution. This is a big driver for the user being the owner of the item or an admin in the org to author a Solution item template.

> @jmhauck did a lot of work in the python library for cloning feature layer views and should be able to help with some of the associated challenges.

**Comment by jmhauck** [comment]
Support for views came in with pull request #28 under the feature-layer type. As mentioned above the user must be the owner of the item or an admin in the org to author a template as this process requires access to the admin api to gather all of the necessary details to re-create the view.

**Comment by chris-fox** [comment]
Verified
