### ISSUE TITLE
StoryMaps and Web Experiences not being placed in correct folder in user content

### ISSUE THREAD

**Issue by chris-fox** [Esri/solution.js#374]
Items are created in the user home folder and not moved to correct output folder. Ideally items would be created in the correct folder in the initial addItem request to save the need for a move request.

@dbouwman, @ghudgins

**Comment by dbouwman** [comment]
Whoops! Added. Will land with my next PR that brings convertToTemplate for Sites and Pages - should be up later today @chris-fox
