### ISSUE TITLE
Workforce projects with multiple integrations for different assignments types are not being templatized

### ISSUE THREAD

**Issue by chris-fox** [Esri/solution.js#382]
Reproducible with the item 1e555bb03afe4912b376374402be94aa

It has a section for Collector with their is an assignmentTypes object. These integrations are not being templatized in the resulting template.

{
            "id": "default-collector",
            "prompt": "Collect at Assignment",
            "assignmentTypes": {
                "1": {
                    "urlTemplate": "arcgis-collector://?itemID=b5142b618da74f92af9e84f7459b64a8&center=${assignment.latitude},${assignment.longitude}"
                },
                "2": {
                    "urlTemplate": "arcgis-collector://?itemID=b5142b618da74f92af9e84f7459b64a8&center=${assignment.latitude},${assignment.longitude}&featureSourceURL=https://services7.arcgis.com/piPfTFmrV9d1DIvN/arcgis/rest/services/ProposedSiteAddress_field/FeatureServer/0&featureAttributes=%7B%22placename%22:%22${assignment.location}%22%7D"
                }
            }
        }

**Comment by jmhauck** [comment]
please check this in Safari as well

**Comment by chris-fox** [comment]
Verified in Safari, everything worked well.
