### ISSUE TITLE
Solution deployment using groups not owned by user

### ISSUE THREAD

**Issue by gisjoel2** [Esri/solution.js#390]
User A: Deploys Sewer Data Management solution
   - Is the owner of 4 Groups (one is Sewer Editors)
   - User A adds User B to Sewer Editors group

User B: Deploys Sewer Data Management solution
   - Solution creates all items for the solution but uses the Sewer Editors group owned by User A

Expected outcome:
Solution creates new Sewer Editors group owned by User B to deploy items into.

**Comment by chris-fox** [comment]
This request is to only search for groups owned by the deploying user when using the reuse option. Don't search for groups the user is a member of.

**Comment by chris-fox** [comment]
Verified
