### ISSUE TITLE
Cannot create solutions which contain a living atlas layer and a geocode service 

### ISSUE THREAD

**Issue by shoe913** [Esri/solution.js#391]
Web App Builder apps which contain a widget that uses a geocode service (search, screening, etc.) and a map with a living atlas layer cannot be converted to a solution item.

**Comment by shoe913** [comment]
@jmhauck 

Is there anyway we can work to get this included into a build a little sooner rather than later? Several solutions we plan on releasing in July require this to build and we'd like to make sure we don't hit any other issues during testing.

**Comment by chris-fox** [comment]
@shoe913, could you put together a simple repro item for @jmhauck? Would help him debug and get a quicker fix.

**Comment by shoe913** [comment]
@jmhauck you can repro the error with this app. 


https://arcgis4localgov2.maps.arcgis.com/home/group.html?id=6c1e20ee307641b884c63e3b4545f2dc

**Comment by chris-fox** [comment]
@shoe913 , could you please verify for 8.3. Thanks.

**Comment by shoe913** [comment]
Veerified
