### ISSUE TITLE
Manage Web Map with hosted duplicate feature layer

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/solution.js#40]
Web Map http://arcgis4localgov2.maps.arcgis.com/home/item.html?id=cbeb7b2f0ae14e75b44061c26f5d6eec has the same feature layer used for two operational layers, but one instance has an itemId and the other does not:

![image](https://user-images.githubusercontent.com/2125181/59050977-a17b2f00-8840-11e9-8cd7-04f3cc355a35.png)

@chris-fox:
> @MikeTschudi, As you have seen itemId is not a required property of an operational layer in the web map. Depending on how the layer is added to the map it may or may not have the itemId property set. In addition, non hosted services may not have an item id at all. The url is the only requirement. What I have done in my python logic is to check for a 'serviceItemId' property on the FeatureService, this will be on all hosted feature services and corresponds to the item id of the service in the Portal.

**Comment by chris-fox** [comment]
Verified
