### ISSUE TITLE
Solutionid type keyword not long enough

### ISSUE THREAD

**Issue by shoe913** [Esri/solution.js#401]
The type keyword created for solutionid needs to be 32 characters. We're currently only getting 8

Item:
https://localdeployment.maps.arcgis.com/home/item.html?id=2e9600ba0a4b46e8bbe6cd1849481f2c

Keywords:
`['Solution', 'solutionid-90zlov5f', 'solutionversion-1.0', 'Template']`

**Comment by chris-fox** [comment]
verified
