### ISSUE TITLE
During Solution Creation Some resources are lost

### ISSUE THREAD

**Issue by shoe913** [Esri/solution.js#402]
During solution creation, some resources are lost or incomplete.  

- This occurs mostly with larger solutions.
- There doesn't seem to be a pattern as to what is lost. 

This group has reproduced the issue sporadically
https://arcgis4localgov2.maps.arcgis.com/home/group.html?id=f4cbf4d6f1fb41f8b0eea1c3a6683d46#overview

**Comment by dbouwman** [comment]
@MikeTschudi I wonder if this is a reoccurrence of the issue you were running into in March(?), and tried to resolve by zipping them all up. 

fwiw - I ran my parallel resource upload test harness, and it successfully ran:
- uploaded 17 image files, ranging in size from 300kb to 6MB
- uploaded two zip files - one 30mb, one 49mb
- all promises fired in parallel

Granted this is running in node... but it's calling the same underlying rest-js functions

I have not pushed that code to github yet b/c I was lazy and put my username/pwd in the code - if you want it, I'll add dotenv and extract to a file that's not checked in

**Comment by MikeTschudi** [comment]
@shoe913, can this issue be closed? The items are no longer available for testing, and we now have better bulk resource handling.

**Comment by shoe913** [comment]
@MikeTschudi I believe so. The new resource handling is much better. We will reopen if necessary.
