### ISSUE TITLE
Python Notebook file is not being written out with a .ipynb extension

### ISSUE THREAD

**Issue by chris-fox** [Esri/solution.js#411]
Python Notebooks can be downloaded from the item and currently after deployment you just get a file named 'file' with no extension. The pattern we should use is the item id of the created item with the extension .ipynb, for example 84461a1ba6f047d590542c714ee36e33.ipynb.

**Comment by MikeTschudi** [comment]
The original name is stored in the solution (`"name": "6cac3d4789b54c8b851af446732e2ba3.ipynb"`), but in the deployed notebook the name is as described above: `"name": "file"`. The `update` REST call containing the Notebook for the item is missing the `fileName` parameter.

**Comment by shoe913** [comment]
Verified
