### ISSUE TITLE
Support dependencies listed in Embedded elements

### ISSUE THREAD

**Issue by shoe913** [Esri/solution.js#419]
Similar to  #48 

In dashboards, if embedded content contains ArcGIS Online references (such as a survey), it should be templatized.

**Comment by chris-fox** [comment]
I think we should handle this with #477

**Comment by shoe913** [comment]
@chris-fox  Looks like #477 addressed this. 

The embedded URL is given variables, however the item is not discovered by the deployment tool (expected). If you package the item independently everything works correctly.

On my sample, deployment worked with item in the dependency list and outside the list. 

I think this is the behavior we would want. When in the dependency list by default, functionality may not be as clear and many items could look cyclical when they are not truly this way (thinking specifically of Arcade links).

**Comment by chris-fox** [comment]
Thanks @shoe913
