### ISSUE TITLE
Views fail to create in Enterprise during updateDefinition

### ISSUE THREAD

**Issue by chris-fox** [Esri/solution.js#424]
The following error is raised:

{"error":{"code":500,"message":"Field 'sourceServiceFields' cannot be updated.","details":[]}}

I see we are sending this property in the updateDefinition call, but I am not clear what it is attempting to set on the view. Do we need this?

**Comment by chris-fox** [comment]
You can repro this with 9a1454188424415fadd7745f219c3ce1, but need to resolve #423 first to get to the view creation.

**Comment by jmhauck** [comment]
sourceServiceFields is a hash that was used for field name comparisons and never should have been going out with update calls.

**Comment by chris-fox** [comment]
Verified
