### ISSUE TITLE
Workforce code doesn't work in Safari

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/solution.js#427]
The function
```
export function _getURLs(v) {
    return regExTest(v, /(?<=featureSourceURL=).*?(?=&|$)/gi);
}
```
fails in Safari due to unsupported lookbehind ([file](https://github.com/Esri/solution.js/blob/986428c54f65c9699dafd42bb0c89e6ee18f5c9b/packages/simple-types/src/workforce.ts#L294-L296))

**Comment by chris-fox** [comment]
verified
