### ISSUE TITLE
Add Web AppBuilder's Code Attachment

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/solution.js#43]
Code attachment is used for WAB downloading

**Comment by chris-fox** [comment]
Related when templatizing don't store the code attachment in the template

**Comment by MikeTschudi** [comment]
- [ ] don't save code attachments in template
- [ ] create code attachment for WAB app when deploying

**Comment by chris-fox** [comment]
@MikeTschudi, the first part in regards to not saving the code attachment with the template is working well, but I am not seeing the code attachment being created during the deployment. To repro deploy Election Outreach, there are 3 web appbuilder apps and I am not seeing code attachments for any of the apps.

**Comment by MikeTschudi** [comment]
Fixed in commit c92dc06d3e9a77342a8c277249bfe3ce8a77b395

**Comment by MikeTschudi** [comment]
Fixed with PR #68

**Comment by chris-fox** [comment]
@MikeTschudi, one more thing I forgot to mention here. In order for it to produce the desired experience you need to create a WMA2Code relationship between the web appbuilder app and the code attachment:

https://developers.arcgis.com/rest/users-groups-and-items/relationship-types.htm

The best way to do this is in the addItem call for the Code Attachment by specifying the relationshipType and the originItemId of the web appbuilder app.

https://developers.arcgis.com/rest/users-groups-and-items/add-item.htm

The way to verify this worked is if the code attachment is created properly and related to the app you will see a download button from the item details of the app.

**Comment by MikeTschudi** [comment]
@chris-fox, thank you for reminder

**Comment by chris-fox** [comment]
Verified
