### ISSUE TITLE
{{portalBaseUrl}} is not being replaced with correct url in Enterprise

### ISSUE THREAD

**Issue by chris-fox** [Esri/solution.js#430]
When I deploy to Enterprise which has base url like, 'https://rpubs16038.esri.com/portal/' the variables in all the solutions are being replaced with 'https://rpubs16038.esri.com/portal/sharing/rest/' which breaks many of the references in the maps and apps.

**Comment by MikeTschudi** [comment]
fixed via commit e92839242f432c1bb2e555c81315b08c7a99ee9a

**Comment by chris-fox** [comment]
Verified
