### ISSUE TITLE
Enhancements to deploySolution demo app

### ISSUE THREAD

**Issue by chris-fox** [Esri/solution.js#431]
- Use the same logic as the deployment app to name the folders in the destination org (The name of the solution, solution 1, solution 2), it currently names it ‘Deployment of Solution item 9a1454188424415fadd7745f219c3ce1’

- Name the solution item the same as the original solution item template name, it currently names it ‘Deployment of Solution item 9a1454188424415fadd7745f219c3ce1’

- Copy all the same item details from the Solution template, for example, thumbnail, snippet, description, tags, typeKewords, etc.

**Comment by MikeTschudi** [comment]
Implementing on top of #500

**Comment by chris-fox** [comment]
Verified

**Comment by chris-fox** [comment]
@MikeTschudi, missed this during my verification because I didn't test Enterprise, but now if I set the destination to Enterprise, it assumes the ID that I am deploying is also in that same Enterprise. I need to be able to set the source to Online and deploy it to Enterprise. Could we set the default for the source back to Online?

**Comment by chris-fox** [comment]
Or should we add a section for credentials for the source organization at the top? Default the url to 'https://www.arcgis.com/ and if you don't pass credentials attempt to connect to the item anonymously.
