### ISSUE TITLE
Enterprise doesn't allow views being creating in parallel on the same service.

### ISSUE THREAD

**Issue by chris-fox** [Esri/solution.js#432]
I encountered in the past with the python cloning code. Enterprise puts a lock on the source feature service whenever you are modifying a views definition. This lock prevents you from modifying other views of the same service and if for example you do attempt to make a change via addToDefinition or updateDefinition you will receive the following error on the view:

{"error":{"code":500,"message":"The service is locked because it is modified by another thread.","details":[]}}

This forces us to have to create the views sequentially for the same service. You can create views for different services in parellel. So this will only be needed if a solution contains more than 1 view on the same source service. Unfortunately this is fairly common in our solutions.

46e58afa7e494fbebe5eb8c25e8035fa has a good repro case with the views ProposedSiteAddress_field and ProposedSiteAddress_public on top of the ProposedSiteAddress feature layer.

**Comment by chris-fox** [comment]
Hi @jmhauck , I tested and verified this resolved it in 46e58afa7e494fbebe5eb8c25e8035fa, but I am still seeing the issue with 36507dff46f54656a74032ac12acd977. It is creating and updating 2 views on the Assignments feature service at the same time.

{"error":{"code":500,"message":"The service is locked because it is modified by another thread.","details":[]}}

**Comment by jmhauck** [comment]
I am still seeing an issue with any join views when going to portal. Seems like it struggles with the duplicate field names across the join view sources...for things like globalid objectid and so on. Will need to take a closer look when joins are supported in portal.

**Comment by chris-fox** [comment]
Verified

**Comment by xiao8579** [comment]
@chris-fox @jmhauck @MikeTschudi 

I was testing solution.js (we are on **version 0.18.5**) with ArcGIS QuickCapture Designer. We have implemented the 'deploy solution workflow' in our app, and I was trying to create a list of contents to an ArcGIS Enterprise portal from a given solution (publicly hosted on ArcGIS Online). The solution item contains two feature layer views from a hosted feature layer, and I am seeing the same error at the addToDefinition process. See error below.
![image](https://user-images.githubusercontent.com/18433455/97924588-c107d700-1d14-11eb-989e-fb3ff9f9b397.png)

However, if I tried the same settings with the deploy solution app you shared with me before, it goes through successfully. 
http://ec2-18-219-57-96.us-east-2.compute.amazonaws.com/demo/deploySolution/
![image](https://user-images.githubusercontent.com/18433455/97925208-d6c9cc00-1d15-11eb-86b3-49aea31bcea8.png)

I am wondering,
Is there anything we need to do additionally on our end to avoid this error; Or is this issue NOT fixed on version 0.18.5 that we need to use a higher version (and what it is)?

**Comment by chris-fox** [comment]
@xiao8579, this fix isn't in 0.18.5.  The test app you are using is on the latest commit in the develop branch. If you update to the latest released version it should be resolved.

**Comment by xiao8579** [comment]
@chris-fox Thanks for the update! We will install the latest library for this issue, but since we're approaching our RC timeline, any update would require additional testing efforts, would the current version (0.20.1) be a relatively stable build for us to use?

**Comment by chris-fox** [comment]
@xiao8579, yes this is a stable release. It is the version Hub is targeting for inclusion in 10.9 pre-release.

**Comment by MikeTschudi** [comment]
@xiao8579, please use the exact version, e.g.,
```
"@esri/solution-common": "0.20.1"
```
*without* the caret ("^0.20.1") indicating that patch versions are acceptable.

I'm updating our build tools to work with permanent release branches, and there have been patch versions that have not worked.

**Comment by xiao8579** [comment]
@MikeTschudi Thanks, Mike!
