### ISSUE TITLE
Failing to create pages and sites in Enterprise

### ISSUE THREAD

**Issue by chris-fox** [Esri/solution.js#439]
I attempted to deploy the following item in Enterprise 10.8.1 and it failed with the error below in the Console.

https://www.arcgis.com/home/item.html?id=da0765bd3d0e46519bb1291492edabcb

![image](https://user-images.githubusercontent.com/6796763/91566924-57cda700-e912-11ea-97c6-12bed9f451ec.png)

I am using this Portal to test:

https://rpubrh76001.ags.esri.com/portal/

@dbouwman, @ghudgins

**Comment by dbouwman** [comment]
Thanks @chris-fox - what version of Solution.js is 10.8.1 using? Master/Develop or some previous version?

**Comment by chris-fox** [comment]
It is using the latest from develop.

**Comment by dbouwman** [comment]
@chris-fox great - thanks... will let you know asap when I have a fix
