### ISSUE TITLE
Add Storymap type

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/solution.js#44]

**Comment by chris-fox** [comment]
Did some research into this item type. With StoryMap you can have a draft and published version. The published version is stored in the data of the item. The draft is stored as a .json file in the item resources. Then name of the file is refrenced via a typeKeyword on the item. For example:

smdraftresourceid:draft_1586544394027.json

So any swizzling we do seems like it needs to be done in both. I am leaning towards just saying we only templatized the published version (item data) and during deployment we overwrite the draft json resources with the resulting item data.

Additionally, you can embed webmaps in the story map. This seems to be isolated pretty well in the json within a resources section. Templatizing the item id of the web map should be straightforward. The challenge will be the map extent, it is not stored the same as the item extent, it is more similar to the feature service extent. It would be nice if we could default this map extent to the extent of the org.

**Comment by chris-fox** [comment]
It sounds like the Hub team may be working on this, so pulling from the project for now.
