### ISSUE TITLE
Add Table type

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/solution.js#45]

**Comment by jmhauck** [comment]
@MikeTschudi  @chris-fox want to make sure I'm not missing a consideration here. Tables that are a part of a feature service should already be handled as of pull request #28. Does this have another facet?

**Comment by chris-fox** [comment]
@jmhauck If a feature service only has a single table in it, It displays as a Table in the item details, but I believe the item type is still Feature Service. I think we just wanted to confirm this was supported, but I believe it should behave the same.

**Comment by jmhauck** [comment]
@chris-fox cool, I'll confirm

**Comment by jmhauck** [comment]
@chris-fox this is supported with the work that came in with pull #28

**Comment by chris-fox** [comment]
Verified
