### ISSUE TITLE
Wrong authentication passed when fetching item template

### ISSUE THREAD

**Issue by mpayson** [Esri/solution.js#458]
[getItemMetadataAsFile](https://github.com/Esri/solution.js/blob/develop/packages/deployer/src/deployer.ts#L75) passes in the deployment recipients session (`authentication`) resulting in a `403` error -- this should be the storage session (`storageAuthentication`). cc @MikeTschudi

```javascript
// ...
return Promise.all([
  Promise.resolve(model.item),
  Promise.resolve(model.data),
  common.getItemMetadataAsFile(model.item.id, storageAuthentication)
]);
// ...
```

**Comment by mpayson** [comment]
Confirmed this was fixed in the latest releases, closing -- thanks!

**Comment by MikeTschudi** [comment]
Thank ***you***, Max!
