### ISSUE TITLE
Add post-process to solution creation to search for and replace item id, feature service url, and portal base url refereneces

### ISSUE THREAD

**Issue by chris-fox** [Esri/solution.js#477]
Today we have a lot of scenarios where we are referencing apps/maps/layers from arcade expressions, web map pop-ups, html references in Hub sites and these item references are not automatically picked up and replaced when the solution item is created. This is because it can be challenging to find and determine if these references should be included or not.

I believe we could handle the majority of these cases automatically by at the end of solution creation, after every item has been templatized is to do a find/replace of any remaining item ids included in the solution that haven't replaced with a variable. 

For example, for each template in the solution, search for the original item id and replace with {{xxxxx.itemId}}. For every feature service in the solution for the base url as well as each layer url and replace with the corresponding variable. And search for any references to the org url and replace with {{portalBaseUrl}}.

I think the only thing we may need to do is target where we are searching for these variables, because we don't want to replace the references inside "dependencies" with variables. I believe we could target the item info and data sections of the templates.

This should be a safe assumption, because if an item is included in the solution it can be assumed that any references to that item from other items within that solution should be updated to the new item when deployed.

**Comment by MikeTschudi** [comment]
In each item's template, searching these properties of an item's template:
* `data`
* `assets` (for Hub Site Application)

Only ids that are items in the Solution are templatized.

**Comment by chris-fox** [comment]
@MikeTschudi, I don't believe we want to do the replacing on the assets of a Hub Site. I believe these urls are intended to point to the original item and are only used during the site creation of the resources don't exist in the solution item. So I think we are good to just search the item and data json.

**Comment by MikeTschudi** [comment]
Chris:
> w/ regard to the portalBaseURL, we should only look for urls that are the same as the org url, i.e https://localdeployment.maps.arcgis.com/ and not just https://www.arcgis.com/, because we don't want to overreplace references to arcgis.com resources.

**Comment by MikeTschudi** [comment]
@chris-fox, would you please provide additional detail for "For every feature service in the solution for the base url as well as each layer url and replace with the corresponding variable"?

**Comment by chris-fox** [comment]
@MikeTschudi, We should look for any feature service urls included in the solution and replace with the correct variable. For example, take the Feature Service:

https://services7.arcgis.com/piPfTFmrV9d1DIvN/arcgis/rest/services/InfrastructureProjects_allfundedprojects_db6e5e2ed53d47b1b846c363547ca1b9/FeatureServer

That has sub layers of:

https://services7.arcgis.com/piPfTFmrV9d1DIvN/arcgis/rest/services/InfrastructureProjects_allfundedprojects_db6e5e2ed53d47b1b846c363547ca1b9/FeatureServer/0
https://services7.arcgis.com/piPfTFmrV9d1DIvN/arcgis/rest/services/InfrastructureProjects_allfundedprojects_db6e5e2ed53d47b1b846c363547ca1b9/FeatureServer/1

We should search for any of these urls and replace with the appropriate variable as we currently do in the web map and web apps for example:

- https://services7.arcgis.com/piPfTFmrV9d1DIvN/arcgis/rest/services/InfrastructureProjects_allfundedprojects_db6e5e2ed53d47b1b846c363547ca1b9/FeatureServer is replaced with {{831e09ec4e5544fcb4dad9541339fcd6.url}}

- https://services7.arcgis.com/piPfTFmrV9d1DIvN/arcgis/rest/services/InfrastructureProjects_allfundedprojects_db6e5e2ed53d47b1b846c363547ca1b9/FeatureServer/0 is replaced with {{831e09ec4e5544fcb4dad9541339fcd6.layer0.url}}

- https://services7.arcgis.com/piPfTFmrV9d1DIvN/arcgis/rest/services/InfrastructureProjects_allfundedprojects_db6e5e2ed53d47b1b846c363547ca1b9/FeatureServer/1 is replaced with {{831e09ec4e5544fcb4dad9541339fcd6.layer1.url}}

Group 4b8e6873a64e49d2a3ceec9988201bfa has a good example of a Hub Site that references a feature service url in one of the statistic cards to test.

**Comment by MikeTschudi** [comment]
Very helpful--thanks, @chris-fox.

Also led to hub.js enhancement https://github.com/Esri/hub.js/pull/394

**Comment by chris-fox** [comment]
@MikeTschudi, been testing this and I am finding it is not replacing feature service layer references that are not index 0. For example this Hub site, has 2 chart-cards that reference id 1 and id 2 from the same service. All references to id 0 are properly replaced, but not id 1 or 2.

https://arcgis4localgov2.maps.arcgis.com/home/item.html?id=3a336642896847ce88e208b9e0e4a232

**Comment by MikeTschudi** [comment]
@chris-fox, thank you. The previous work was only setting up symbols in a feature service's `data` section; it now also looks in the `properties` section, which catches the missing urls.

**Comment by chris-fox** [comment]
Looks great!
