### ISSUE TITLE
Support dependencies listed in popups

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/solution.js#48]
For example, surveys

**Comment by chris-fox** [comment]
examples Citizen Problem Manager + Citizen Problem Satisfaction Survey, Election Assistance + Election Wait Times

**Comment by chris-fox** [comment]
In the June release we will rely on the solution author handling these references.

**Comment by chris-fox** [comment]
I think we should handle this with #477

**Comment by chris-fox** [comment]
Done
