### ISSUE TITLE
Webmap thumbnails are being overwritten when the web map is saved

### ISSUE THREAD

**Issue by chris-fox** [Esri/solution.js#488]
Typically when you first create a web map it makes a call to the print service to create a thumbnail of the map. In our solutions we are providing thumbnails for the web map and want to persist this even after a save. However, after you deploy if you go to the web map and save it, the thumbnail is updated.

This is not reproducible with the python cloning logic so I am thinking there is a minor difference between how we are applying the thumbnail in solution.js and python that is causing this. I need to do some more research to understand what the difference is and how we can resolve this for web maps.

**Comment by chris-fox** [comment]
Narrowed this down to the use of the thumbnailUrl parameter. I could repro this through python with this param. If we uploaded or passed the thumbnail as a binary it was not reproducible. I have sent a question to the online team to understand if this is a bug or if there is something else we need to do to prevent this behavior.

**Comment by chris-fox** [comment]
@MikeTschudi, this is what I learned from the ArcGIS Online team:

The issue is because the thumbnail name is not preserved in addItem and updateItem when passed as a url. This gets the default thumbnail name and is not seen as a custom thumbnail and thus is overwritten when the web map is saved. That is expected behavior.

There is also an api for items, updateThumbnail that allows you to preserve the name when passing the url (but is not working right now, they have a bug logged for 8.4). If we do this, it will be a different name and be seen as a custom thumbnail and not be overwritten.

The updateThumbnail api is currently undocumented, but they are working on getting it documented. My concern is if we go this direction it would required an additional request for every item to apply the thumbnail. 

I am wondering if it would be challenging to change this logic to apply the thumbnail as a file via the thumbnail parameter in the addItem call. This is what I see other products do like Workforce for example and doing this maintains the thumbnail name and doesn't encounter this issue.

**Comment by chris-fox** [comment]
@ted-howard, if we resolve this than you won't see the thumbnails being renamed to ago_download issue as part of your download/upload tools.

**Comment by MikeTschudi** [comment]
* [x] Creation of Solution template: commit 7afb01f501b501b778b2bc124b0bf2d1d79acbf9

**Comment by chris-fox** [comment]
@MikeTschudi, I know this is still in progress, but I was testing something else recently and noticed the Deployed solution item thumbnail is showing a little fuzzy in the My Solutions tab now. It looks like thumbnail size being written to the solution item is 200x133. I know when we were updating the thumbnail by URL we were requesting a thumbnail with a width of 400px. Could we do the same here as well when we upload?

**Comment by MikeTschudi** [comment]
@chris-fox, thank you for this catch; the 400px request was mistakenly removed as part of the changes and is now back in via PR #545.

**Comment by shoe913** [comment]
Verified
