### ISSUE TITLE
Failure to create ArcGIS Hub group if org 'Members can share content publicly' security setting is disabled

### ISSUE THREAD

**Issue by chris-fox** [Esri/solution.js#492]
If the organization has disabled the setting 'Members can share content publicly' for all users during deployment solution.js attempts to create a Hub Group with access of public which fails and breaks the deployment. To repro you need to make sure you are not an admin in the org, because admins can still share with the public.

{"error":{"code":500,"messageCode":"COM_1026","message":"User cannot share group to public.","details":[]}}

![image](https://user-images.githubusercontent.com/6796763/94961259-4ef86400-04c2-11eb-863d-cfaebd7ed7ef.png)

There is also a user privilege than can be set to not allow the user to share groups with the public. When this privilege is not available for the user the Groups are only being shared to the organization. So the code is handling it properly in this case.

![image](https://user-images.githubusercontent.com/6796763/94961234-44d66580-04c2-11eb-88f0-a782e12586d8.png)

@ghudgins

**Comment by dbouwman** [comment]
Interesting - @chris-fox do you know how the org wide setting manifests? i.e. is there some other priv? or some other thing we need to fetch to know about this? As you see, we handle the case where the user lacks the individual priv...

**Comment by ghudgins** [comment]
I think we know what we missed. we had some failover logic in the hub's frontend that  might've not made the big move into hub.js / solutions.js. we'll take a look next week

**Comment by chris-fox** [comment]
@ghudgins, @dbouwman, would it be possible to address this issue in the next couple weeks? We would like to include in our 8,4 release.

**Comment by chris-fox** [comment]
@MikeTschudi

**Comment by MikeTschudi** [comment]
@chris-fox, solution.js has had the bumped hub.js version, and yesterday we bumped the hub.js version in the app as well. As best as I can tell from loading the minimized JavaScript, today's appDev is using the latest release of hub.js: 6.18.0. Would you kindly check the problem?

**Comment by chris-fox** [comment]
@MikeTschudi, this is working well now. Thanks.
