### ISSUE TITLE
If a value doesn't exist in the replacement dictionary and it is referenced in an optional variable, it breaks all optional variables after

### ISSUE THREAD

**Issue by shoe913** [Esri/solution.js#508]
Organization variables (like the ones below) are not swapped out when the target organization does not have Hub Premium. 

![image](https://user-images.githubusercontent.com/11777080/95924616-c6ed4680-0d6c-11eb-919d-cc936b367fa8.png)

{{organization.name||My Organization}}

{{organization.portalProperties.sharedTheme.logo.small||https://www.arcgis.com/sharing/rest/content/items/28989a5ecc2d4b2fbf62ac0f5075b7ff/data}}

**Comment by chris-fox** [comment]
@shoe913, i reproduced this the first time i deployed the solution to the org, but it worked properly the 2nd time and I can no longer repro. Are you seeing the same. Does your org have a shared theme logo, this is different from the org logo at the top of the settings.

![image](https://user-images.githubusercontent.com/6796763/96010569-ec7f5c00-0e0f-11eb-92bd-9a6e2b8aa5e1.png)

**Comment by shoe913** [comment]
@chris-fox  

After ensuring I had the logo in the correct place, it did start to work. 

I still think we need to look into this though because I made no changes to the org name, and that did not swizzle until the image was swizzeling.  I think it is quite possible we have users who haven't set the shared image, but do want the org name copied.

**Comment by chris-fox** [comment]
@shoe913, could you narrow it down then. Is this true that orgs w/o the shared theme logo fail? My understanding is they shouldn't have anything to do with each other. I want to get to the consistent simplest repro case before we pass along.

**Comment by shoe913** [comment]
@chris-fox 

I can no longer reproduce this with my current orgs. However, when I create a trial org, I can consistently repro.  It seems that the shared logo is changing a few things. 

Before Logo Added (trial with all defaults):
- Default logo present
- Org name missing (replaced with "organization.name")

After Logo Added (same trial, only add the logo):
- Logo Present
- Org name correct

After Logo Removed (same trial, remove the shared logo:
- Logo Missing (No default presented)
- Org name correct

**Comment by chris-fox** [comment]
@MikeTschudi, I was able to create a really simple repro case for this. Here are the steps:

1. This solution item has a single web map, https://www.arcgis.com/home/item.html?id=1c6caa14de614484a7ec76c2f960910c

1. The item description has the following html:

`{{organization.name||My Community}}<br />{{organization.nonexistantproperty.sharedTheme.logo.small||https://www.arcgis.com/sharing/rest/content/items/28989a5ecc2d4b2fbf62ac0f5075b7ff/data}}<br />{{organization.name||My Community}}`

1. Deploy the solution

1. View the resulting Web Map's item description and you will see something like the following:

`ArcGIS Team Local Gov<br />https://www.arcgis.com/sharing/rest/content/items/28989a5ecc2d4b2fbf62ac0f5075b7ff/data<br />
organization.name`

What it looks like is happening, is the first {{organization.name||My Community}} is replaced properly with the organization name setting. 

When it gets to the second it can't find organization.nonexistantproperty.sharedTheme.logo.small in the replacement dictionary, so it correctly falls back to https://www.arcgis.com/sharing/rest/content/items/28989a5ecc2d4b2fbf62ac0f5075b7ff/data. 

Then the third one, should be properly replaced with the org name again, but it instead it is returning the name of the variable incorrectly.

**Comment by MikeTschudi** [comment]
Superb information; thank you @shoe913 & @chris-fox!

**Comment by MikeTschudi** [comment]
fixed adlib: https://github.com/Esri/adlib/pull/54

**Comment by MikeTschudi** [comment]
adlib updated to version 3.0.6; hub.js needs update to use same version

**Comment by chris-fox** [comment]
Verified
