### ISSUE TITLE
Replace use of geometry service with 4.x api

### ISSUE THREAD

**Issue by chris-fox** [Esri/solution.js#513]
Can we explore if we can replace anywhere we currently use the portal's geometry service with equivalent functions in the JavaScript 4.x api? Specifically I am thinking findTransformations and project. We have had issues in the past with Enterprise not having a geometry service running so this should make it more reliable.

**Comment by dbouwman** [comment]
@chris-fox My concern with this is the ability to run/use the JSAPI in node... so if we want to explore this, it needs to be configurable such that the Solution App passes in a function that is called in place of the geometry service, but if that option is not provided then solution.js makes calls to the geometry service.

**Comment by chris-fox** [comment]
After speaking with enterprise team, we should be able to rely on the Enterprise exposing a geometry service via portal self helperServices which is what we are currently using. So we will keep this behavior.
