### ISSUE TITLE
Layer Optimization Updates

### ISSUE THREAD

**Issue by shoe913** [Esri/solution.js#526]
@chris-fox 

After playing around with layer optimization, I think we should consider forcing all layers to be deployed without optimization -- either stripping on deployment, or during solution item creation (preferred, I believe).  

We don't intentionally ship layers which consume credits, and according to the documentation, optimized layers can potentially use 100% more credits than normal layers. I feel that this is a decision the end user should be making about their data.  

Furthermore, it seems that currently during deployment, we lose the ability to turn optimization off. We would certainly need to go through after service creation and turn it on. 

I think the level effort required to go through after item creation and turn on optimization (and make sure we can turn it off again) will not outweigh the benefit.

**Comment by chris-fox** [comment]
Thanks @shoe913, I agree. Updating the issue to request we remove this definition during solution creation:

During feature creation we should remove the following property from any layer in a Feature Service. You can just remove the property complete, it doesn't need to exist in the feature service. This will ensure that it is not enable when the feature service is created, which actually corrupts the service if it is enabled in the original addToDefinition call.

"multiScaleGeometryInfo" : {
    "levels" : [
      1, 
      3,
      5,
      7,
      9,
    ]
  }, 

To test you can enable this property from the item details > settings page. Note it will only be available for Polygon and Polyline layers.

![image](https://user-images.githubusercontent.com/6796763/97308701-8b0bb400-1837-11eb-85a5-b55ee100283a.png)

**Comment by shoe913** [comment]
This solution item has an optimized and and un-optimized layer for reference. 

https://arcgis4localgov2.maps.arcgis.com/home/item.html?id=953f8724fc824e0c95ada6038701e1b6

**Comment by chris-fox** [comment]
Verified
