### ISSUE TITLE
Add check in item's info/details for unresolved variables to post processing for all item types

### ISSUE THREAD

**Issue by chris-fox** [Esri/solution.js#534]
This is an extension of #444 to handle this for all item types. Because via #477 we are post processing items during solution creation to replace item ids, portal urls, app urls, and feature service urls in both the item's info and data, we also need to handle these on deployment in a post process because these variables won't always be dependencies.

To repro, create a solution from the following group:

https://localdeployment.maps.arcgis.com/home/group.html?id=04f36eae6346438c873a461da54c4a2f

It contains a web map with references to other apps in the group in its item description. When created these are replaced with variables via the post process implemented in #477 

When the solution is deployed, these variables aren't replace because the apps aren't dependencies of the web map. I would like to extend #444 to handle all item types to ensure there item's info/details is properly swizzled even when the item is not a dependency.

**Comment by chris-fox** [comment]
@MikeTschudi, If the description property of the item is null it fails to create the solution:

![image](https://user-images.githubusercontent.com/6796763/101364011-13866700-3870-11eb-99c3-947d912e6537.png)

**Comment by MikeTschudi** [comment]
Thanks for catch, @chris-fox!

**Comment by shoe913** [comment]
Verified
