### ISSUE TITLE
Need to pass the typeIdField in updateDefinition call for view layers

### ISSUE THREAD

**Issue by chris-fox** [Esri/solution.js#540]
We recently found a bug if a view has a different typeIdField than what it being set on the source service is not being properly updated. Today after the addToDefinition call we do an updateDefinition to update things like the renderer and feature templates. We should add typeIdField to this update as well to handle properly setting this field.

{
  "typeIdField" : "status"
}

**Comment by jmhauck** [comment]
@chris-fox have a solution with this going on?

**Comment by chris-fox** [comment]
You can repro with this item:

https://www.arcgis.com/home/item.html?id=21a16c666dc04f3d81a952d8d6d96360

There is a service and a view. The template has the typeIdField set to 'issue' in the source service and 'status' in the view. When you deploy the typIdField is set to 'issue' for both the source and the view.

We should also verify this fix with Enterprise as well.

**Comment by jmhauck** [comment]
Need to chat with @MikeTschudi a little more on this. Getting an error on common.getBlobAsFile in deploySolutionFromTemplate when going to portal.

**Comment by jmhauck** [comment]
Good now!

**Comment by chris-fox** [comment]
Verified
