### ISSUE TITLE
Add support for Feature Collection item type

### ISSUE THREAD

**Issue by chris-fox** [Esri/solution.js#552]
It is a json item type. We simply need to copy the item, we don't need to do anything else with it or look for dependencies.

Here is an example Feature Collection that can be used in testing:
https://localdeployment.maps.arcgis.com/home/item.html?id=966d457398bd452c8a68c0806faa3184

**Comment by MikeTschudi** [comment]
In release/0.21 branch

**Comment by shoe913** [comment]
Verified
