### ISSUE TITLE
Add Web Mapping Application item with simple url reference

### ISSUE THREAD

**Issue by chris-fox** [Esri/solution.js#56]
We have recently started delivering "Getting to Know" story maps with the solution as essentially the help for the Solution. We don't want to clone the story map, but rather are just delivering a Web Mapping Application with its url set to our story map in our try it live org. So this is essentially a really simple item with no data and a url reference.

**Comment by jmhauck** [comment]
@chris-fox do you know of one of these in the deployment org? The getting to know web apps I'm seeing in there all have broken links.

Will the determination be made based on some specifc tags or something specific within the url?

**Comment by chris-fox** [comment]
@jmhauck, the getting to know are broken because they are using shortlinks which is currently broken across Esri. You could always add you own item and just point it to esri.com or some other url.

**Comment by jmhauck** [comment]
@chris-fox thanks...I missed that comment earlier. 

So am I just supposed to check if it's a tryit url to know if it should be handled like this?

**Comment by chris-fox** [comment]
@jmhauck, no. If it is a Web Application with no item data, it will have no dependencies and the url doesn't need to be swapped out with any variables. So you don't need to inspect the url, just test if the item's data is empty.

**Comment by jmhauck** [comment]
@chris-fox ok sounds good

**Comment by chris-fox** [comment]
Verified
