### ISSUE TITLE
Add Experience Builder type

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/solution.js#57]
Type is "Web Experience"

**Comment by chris-fox** [comment]
Did some research on this. When authoring an Experience as a draft, the configuration is stored as a resource of the item 'config/config.json'. Ultimately when you 'publish' the experience the configuration is stored in the item data itself. 

Initially I am thinking we only worry about the 'published' experience. I am not really seeing a good scenario where someone would want to templatize the published and draft version of the experience and deploy that.

**Comment by chris-fox** [comment]
Updating comment from above, we need to support both, but we have a pattern for handling json stored as a resource, i.e QuickCapture. I think we just need to templatize both so when a user deploys their draft and published versions match.

In terms of the structure, with an initial look it looks like they have done a good job of isolating the datasources in its own property at the root of the item data. This should make it fairly easy to find and templatize the dependencies.

 "dataSources": {
        "dataSource_1": {
            "type": "WEB_MAP",
            "itemId": "23d66e6e2b7f48c4a225ecb3a61f1cd7",
            "id": "dataSource_1",
            "label": "My Elected Representative",
            "portalUrl": "https://arcgis4localgov2.maps.arcgis.com",
            "url": "https://arcgis4localgov2.maps.arcgis.com/home/webmap/viewer.html?webmap=23d66e6e2b7f48c4a225ecb3a61f1cd7",
            "layerId": "viewer.html?webmap=23d66e6e2b7f48c4a225ecb3a61f1cd7"
        },
        "dataSource_2": {
            "id": "dataSource_2",
            "type": "FEATURE_QUERY",
            "label": "Location Tracking",
            "url": "https://services.arcgis.com/b6gLrKHqgkQb393u/arcgis/rest/services/location_9a10735972664fb8a2d6842b61fa0934/FeatureServer/0",
            "layerId": 0,
            "itemId": "9e0c4fa603c942a782ae79360f23b8e7",
            "portalUrl": "https://arcgis4localgov2.maps.arcgis.com"
        }
    }

**Comment by chris-fox** [comment]
Here is a common scenario we will be supporting with experience builder, a app with 2 embedd widgets with 2 different versions of a dashboard (Mobile and Large display).

https://experience.arcgis.com/experience/c00baf45f12a4899aae1c812e29d6cde
