### ISSUE TITLE
Create Solution2Item relationship between the deployed solution and all deployed or referenced by the Solution

### ISSUE THREAD

**Issue by chris-fox** [Esri/solution.js#575]
At 8.4 a new relationship type was added for us called Solution2Item. It is to be used to associate a Solution with all the items it references. This will be items created during deployment and items that were discovered from prior deployments (for example feature services deployed by another solution that are also a part of the new solution that was deployed).

During deployment we should create this relationship. This will help us in the future to better support deleting a solution and all its related items. We can navigate the relationship backwards on the item to ensure we don't delete an item that is a part of multiple solutions.

Documentation: https://developers.arcgis.com/rest/users-groups-and-items/relationship-types.htm
|Relationship type|Description|Origin type|Destination type|Rule|
|-|-|-|:-:|-|
|Solution2Item|Models the association of Solution to the items created as part of the Solution.|Solution|*|Note: This relationship type is only applicable to ArcGIS Online organizations.|

Add: https://developers.arcgis.com/rest/users-groups-and-items/add-relationship.htm
Get: https://developers.arcgis.com/rest/users-groups-and-items/related-items.htm

**Comment by chris-fox** [comment]
Verified that this relationship is available in Portal 10.9 as well.

**Comment by MikeTschudi** [comment]
Available in ec2 demos; getItemInfo has been updated to report this relationship type in addition to the other types

**Comment by MikeTschudi** [comment]
@chris-fox & @shoe913, it appears that one cannot create a relationship between items and groups.

Perhaps add a tag to the deployed group that has the id of the corresponding deployed Solution item, e.g., `deployed-b9faa4ca65bc4e6b93cb326a05b210e3`?

**Comment by chris-fox** [comment]
@MikeTschudi, I am leaning towards not including the tag and not worrying about the relationships with groups. Specifically because in the scenario where a group is shared between solutions we have avoided updating already deployed items/groups I wouldn't want to have to update an already deployed group with a tag.

**Comment by MikeTschudi** [comment]
Sounds good, @chris-fox; thanks.

Commit d307fb3554a33b459fcb048fa2b84aaf382fa898 filters out groups from the add-relationship call.

**Comment by chris-fox** [comment]
Verified
