### ISSUE TITLE
Enterprise sites are not getting the correct url

### ISSUE THREAD

**Issue by chris-fox** [Esri/solution.js#576]
When testing deploying a solution from our app that is installed with ArcGIS Enterprise 10.9, sites are getting the incorrect url. For example our app is accessed via the url:

https://dev0016196.esri.com/portal/apps/Solutions/index.html

When I deploy the Performance Management solution I get a site with the url of:

https://dev0016196.esri.com/portal/apps/Solutions/index.html#/performance-management

Instead of:

https://dev0016196.esri.com/portal/apps/sites/#/performance-management

@ghudgins

**Comment by dbouwman** [comment]
Issue was in Hub.js, where the code was not using portalSelf to construct the url to the sites app, but was instead using the current window.location. Changed to using portalSelf.portalHostname. PR is up and will merge + release today

**Comment by dbouwman** [comment]
Addressed in Hub.js @ v6.22.2, released 1/12/2021 ~15:00 UTC

**Comment by dbouwman** [comment]
Re-opened so @chris-fox  can verify then close

**Comment by chris-fox** [comment]
Verified
