### ISSUE TITLE
ParentGlobalIDIndex changing during deployment. 

### ISSUE THREAD

**Issue by shoe913** [Esri/solution.js#581]
When deploying the Operations Management Solution, the ParentGlobalIDIndex on one of the feature layers is changing from "Unique:False" to "Unique:True". 

This is preventing the solution from allowing multiple related records to be submitted. 

1) Deploy the  Operations Management Solution. 
https://arcgis4localgov2.maps.arcgis.com/apps/solutions/index.html?solution=wcj3uhg5h05y3y36ubmzc3k5q545vfmp
2) Go to the JSON for the Operations Management Feature and look at the listed indices for the operations_missions layer
 Note: The ParentGlobalIDIndex value for unique is True. 

3) Look at the JSON for the feature layer in the Solution Item, the ParentGlablIDindex value for unique is False

**Comment by chris-fox** [comment]
@jmhauck, maybe this was introduced with our work to handle errors in feature service definitions? In this particular case we shouldn't be switching the index to True, because the relationship this field is used in has a role of "esriRelRoleDestination" so it is the 'M' of '1:M'.

**Comment by jmhauck** [comment]
this stems from the change for #455

**Comment by shoe913** [comment]
Verified
