### ISSUE TITLE
Feature Services deployed in Enterprise do not provide UI to Create View

### ISSUE THREAD

**Issue by chris-fox** [Esri/solution.js#589]
I have been trying to debug this, but am not completely sure what is the cause. My theory is we aren't explicitly setting the isView parameter in createService to false, that seems like the main difference.

https://developers.arcgis.com/rest/users-groups-and-items/create-service.htm

You can reproduce with this solution below:

https://localdeployment.maps.arcgis.com/home/item.html?id=571aafba922e4467b5ad150e37280468

Deploy to Enterprise 10.9 and then view the item details of the service, the Create View Layer button won't display:

![image](https://user-images.githubusercontent.com/6796763/107261409-47673f80-6a0d-11eb-9e12-1ab177eb5ef6.png)

It should look like:

![image](https://user-images.githubusercontent.com/6796763/107261459-551cc500-6a0d-11eb-8559-22c648e80eef.png)

The python clone_items function is able to clone the same service with the Create View Layer enabled.

**Comment by jmhauck** [comment]
@chris-fox started to look at this one...just debugging from the portal app side and looks like something is setting a typeKeyword of 'providerSDS'. Later on this typeKeyword is part of the check that controls if the button shows. Still have some digging to do but thought I'd mention

**Comment by jmhauck** [comment]
@chris-fox When you create a feature service that is backed by ArcGIS Data Store the create service request adds a type keyword 'providerSDS'. After a service is created we later update its item to add things like snippet, description, popupInfo, etc. That later update overwrites the typeKeyword that was added by create service with the typeKeywords of the source item template from the solution.

**Comment by chris-fox** [comment]
@jmhauck, that makes sense and explains why the python code is working as I am merging the original typeKeywords with the new ones created by default. Think we do something similar here?

**Comment by chris-fox** [comment]
Verified
