### ISSUE TITLE
Use org's default extent for item extents and feature service initial extent

### ISSUE THREAD

**Issue by chris-fox** [Esri/solution.js#59]
When deploying a solution any new items and feature service/view's initial extent should be set to the default extent of the organization/portal.

When implementing this consider we may want to make this an optional parameter to keep the original extent during the deployment, but the default behavior should be to use the org's extent.

**Comment by chris-fox** [comment]
Also just remembered this is a property that Hub templatizes

**Comment by jmhauck** [comment]
@chris-fox If the spatial reference of the ORGs defaultExtent is different than that of the feature service should I be switching it as well?

**Comment by chris-fox** [comment]
I believe the org extent will only ever be WGS 84. We should keep the spatial reference of the service by project the WGS 84 extent into the spatial reference of the service and use that as the service initial extent.

**Comment by chris-fox** [comment]
@jmhauck, I tested this today and found the item extent wasn't being templatized when I use the Create Solutions app. So when I deploy the extent is being set to the same as it was previously in the deployment org. It looks like the latest changes from the app where pushed over. So I am not sure why this isn't working.

**Comment by chris-fox** [comment]
@jmhauck, did some more testing, I found the feature service initial and full extent are being templatized. However, when I deploy to our dev our (https://arcgis4localgov2.maps.arcgis.com/) I am not seeing the correct extent applied, it should be around Naperville, this is what the Pro deployment tool produces:

XMin: -9821384.71421798
YMin: 5117339.12309
XMax: -9797228.38471584
YMax: 5137789.39951188
Spatial Reference: 102100

This is what the online deployment is producing:

XMin: -15000000
YMin: 2700000
XMax: -6200000
YMax: 6500000
Spatial Reference: 102100

Also this issue needs to also handle the extent property for all item types.  This property is always expressed in WGS 84 and is used to set the extent of things like web maps for example. Sometimes this property is null in which case we don't need to handle it.

**Comment by jmhauck** [comment]
Noticed an issue with this when using private orgs. Have a pull in the resolves it. Will move it back once that is merged.

**Comment by chris-fox** [comment]
@jmhauck, I found the item extent is incorrect it looks like you are switching the XMin and XMax. When I manually edit the item in ago-assistant and switch the xmin and xmax it is correct.

Example:

    "extent": [
        [
            -88.0099999998562,
            41.7080000000663
        ],
        [
            -88.22699999983698,
            41.84499999991977
        ]
    ],

When you pass the item extent, not sure if you are already doing this but according to the doc you can just pass a comma delimited string:

Syntax: extent=<xmin>, <ymin>, <xmax>, <ymax>

Example: extent=-110.05, 44.13, -110, 44.9

https://developers.arcgis.com/rest/users-groups-and-items/common-parameters.htm#ESRI_SECTION1_1FFBA7FE775B4BDA8D97524A6B9F7C98

**Comment by jmhauck** [comment]
@chris-fox  Dang...I just saw the order and not the comma delimited bit. Interesting that it switches things around when you set as:

`orgExtent: [
                    [wgs84Extent.xmin, wgs84Extent.ymin],
                    [wgs84Extent.xmax, wgs84Extent.ymax]
                  ]`

Will get it switched.

**Comment by chris-fox** [comment]
@jmhauck, I am seeing the  extent now being correctly passed as a comma delimited text, but it looks like the xmin and xmax are still being passed swapped which is producing the incorrect results.

extent: -88.0099999998562,41.7080000000663,-88.22699999983698,41.84499999991977

-88.226 < -88.009

**Comment by jmhauck** [comment]
Holy shnikes. I believe this is it now. I thought it had switched something around previously when I submitted in the wrong format. I should have looked closer.

**Comment by chris-fox** [comment]
@jmhauck, as per our conversation I would like to make the following changes to the variables

Item default extent when templatized:
{{organization.defaultExtent||[[-88.2437, 41.7083],[-88.0742, 41.7864]]}}

The '||' indicates the fallback value for a property. In this case it is the original extent of the item and allows us to optionally keep the original extent when deploying.

In addition, I think both the fullExtent and initialExtent could be set like below. We would keep the original fullExtent or initialExtent object as the fallback.

{{9cb8ea9deb79451cad8899351680af0c.organization.defaultExtent||{
    "xmin" : -14675248.471277254, 
    "ymin" : 1831373.4680054081, 
    "xmax" : -6358569.31411178, 
    "ymax" : 8073093.6119444724, 
    "spatialReference" : {
      "wkid" : 102100, 
      "latestWkid" : 3857
    }
  }}"

**Comment by jmhauck** [comment]
@chris-fox we currently get the extent from the org when deploying. What will trigger if that would be used or if the values from the source service should be used?

**Comment by chris-fox** [comment]
@jmhauck, I think for now we can remove the optional parameter here and just use the org default extent. I thought initially I might want to make this a configuration option prior to deployment, but don't think we need to expose this.

**Comment by jmhauck** [comment]
@chris-fox ok...thats they way it currently is, I had just written code that would support the idea of maintaining the source extent as an optional static value so it wasn't in there yet.

As is...when we deploy we get the extent from the portal we are deploying to. That extent is used as the items extent as well as the extent, fullExtent, and initialExtent for any services that are created. 

The only difference right now is in the structure of the template paths and what is in the template dictionary vs what you have listed above. 

Just want to make sure we are on the same page before I make these adjustments.

We currently have: 

```json
{
  "organization": {
    "portalBaseUrl": ...,
    "geocodeServerUrl": ...,
    "naServerUrl": ...,
    "printServiceUrl": ...,
    "geometryServerUrl": ...
  },
  "folderId": "39bafe6d3a7e4175a82905f6dd9c349d",
  "isPortal": false,
  "initiative": {
    "orgExtent": ...,
    "defaultExtent": ...
  },
  "solutionItemId": "3fbeae447a594fcc9baba349d50b5022",
  "dc7900ad60054e6c9386511cae5c903d": {
    "initialExtent": ...,
    "fullExtent": ...
  }
}
```

I can get rid of initiative and move the orgExtent (comma delimited values) and defaultExtent (standard extent object) under organization.

For this pattern:

9cb8ea9deb79451cad8899351680af0c.organization.defaultExtent

We will continue to maintain the global organization values listed above. I will add organization.defaultExtent under the individual services that will maintain the projected instance of the organizations defaultExtent that will match the corrisponding services spatial reference.

**Comment by chris-fox** [comment]
@jmhauck, per our conversation I would recommend we do the following:

1. Move **defaultExtent** under organization. This will reflect the same extent object returned from the portal.self call. We will make this update in the future to reserve "organization" to reflect the portal.self properties and construct this automatically in the template dictionary.

2. Add a new property to the dictionary called **solutionItemExtent**. This property will be the comma delimited format of the extent required by items, [[-88.2437, 41.7083],[-88.0742, 41.7864]]. It will by default be calculated using the organization.defaultExtent property. In the future we can allow users to specify their own extent which override the organization.defaultExtent when calculating the solutionItemExtent in the dictionary. We should replace the extent propety of items with this property during templating.

3. Add a new property to each feature service in the dictionary called **solutionExtent**. This will be a standard extent object and will be calculated by projecting the organization.defaultExtent property to the spatial reference of the feature service. Similar to above in the future users can specify their own extent which will be used instead of organization.defaultExtent. We should replace the initialExtent and fullExtent properties of feature services with this property during templating.

{
  "organization": {
    "portalBaseUrl": ...,
    "geocodeServerUrl": ...,
    "naServerUrl": ...,
    "printServiceUrl": ...,
    "geometryServerUrl": ...
    **"defaultExtent"**
  },
  "folderId": "39bafe6d3a7e4175a82905f6dd9c349d",
  "isPortal": false,
  **"solutionItemExtent": ...**
  "solutionItemId": "3fbeae447a594fcc9baba349d50b5022",
  "dc7900ad60054e6c9386511cae5c903d": {
    **"solutionExtent": ...**
  }
}

**Comment by chris-fox** [comment]
Verified
