### ISSUE TITLE
Regression in .url property for Feature Services

### ISSUE THREAD

**Issue by chris-fox** [Esri/solution.js#613]
Just found this issue today and it looks like it is impacting the version of solution.js going out in 9.1 and the develop branch (being built for enterprise). This is really subtle, but in WAB we have a widget that has a baseURL property that is looking for a feature service url. It looks like:

"searchLayers": [{
"url": "{{d02982cc108b455a9bf4d1fc0734a096.layer0.url}}",
"geometryType": "esriGeometryPoint",
"id": "TrashRecyclingFacilities_public_6509",
"layerId": "0",
**"baseURL": "{{d02982cc108b455a9bf4d1fc0734a096.url}}"**,

In the current release of the app, that variable is swapped out with a '/' at the end of the url:

"baseURL": "https://services.arcgis.com/b6gLrKHqgkQb393u/arcgis/rest/services/TrashRecyclingFacilities_public_95a956ec4b134e498c8f5a742366f300/FeatureServer/"

In develop and the 9.1 release branch this trailing slash is not ended to the url:

"baseURL": "https://services.arcgis.com/b6gLrKHqgkQb393u/arcgis/rest/services/TrashRecyclingFacilities_public_d3e0aa76d36f48ffab6ded0e52c0e982/FeatureServer"

This causes problems and breaks functionality in WAB as the url can't be resolved without the trailing slash.

**Comment by chris-fox** [comment]
You can repro with this solution, 36b8b4de46254bf0882f82b79a72bd45.

**Comment by MikeTschudi** [comment]
After deployment of a Feature Service, we update the copy in the browser with what is stored in AGO. AGO strips the trailing "/" for the FS url, which is causing the problem when the FS's url replaces variables later on in the deployment process.

**Comment by shoe913** [comment]
Verified
