### ISSUE TITLE
Remove 50-file zipfile limit via Hub.js chunkArray function

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/solution.js#616]
See https://github.com/Esri/solution.js/pull/615#discussion_r601510049

**Comment by MikeTschudi** [comment]
The resource problem affects both createSolution (saving an item's resources into the Solution) and deploySolution (moving resources from a Solution into a deployed item). For example, the QuickCapture Project "Rapid Wildlife Reporter" item doesn't necessarily have all of its resources in the Solution item.  Using zip files, and chunking to keep each zip under the 50-file limit, must be done for both creating and deploying Solutions.

As for simply chunking zipped resources, it appears that AGO mishandles multiple zips in a row just as badly as it mishandles multiple resource-adds in a row.

**Comment by chris-fox** [comment]
Verified
