### ISSUE TITLE
A user can belong to a maximum of 512 groups

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/solution.js#617]
@dbouwman discovered that deployment fails if the user already belongs to the maximum number of groups.

Hub site creation checks for this, but a recent modification to this repo ([Solution deployment using groups not owned by user](https://github.com/Esri/solution.js/issues/390)) changes the nominal number of groups to ones that the user *owns*, not the number that he/she *belongs to*. As a result, Hub site creation is checking a false number and fails. The Hub team has a user who has encountered this.

But this is a general failure point for deployment.

@chris-fox, for 9.1?

**Comment by chris-fox** [comment]
@MikeTschudi, what is the fix/change in this case?

**Comment by MikeTschudi** [comment]
If the number of groups that the user belongs to + the number of groups in the solution + a group for the deployment > 512, provide an indication that deployment is not possible.

**Comment by chris-fox** [comment]
I would say no for 9.1 then, because we would need to work on the UI/strings for how we communicate it to the user.

**Comment by dbouwman** [comment]
fwiw - I think we've hit this with one actual customer, ever. 

We do run into this when our e2e test accounts, and some of our interactive testing accounts, accrue >511 groups over time... that is how we originally found this issue, and how it cropped up again earlier today.

**Comment by MikeTschudi** [comment]
Suggestion from Dave is to filter user-owned groups into new template property `user.ownedGroups` rather than modifying `user.groups`; this will make the code clearer and avoid surprises such as he found.
