### ISSUE TITLE
Fix URL generated for retrieving a deploying Solution's thumbnail

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/solution.js#621]
The URL generated for retrieving a deploying Solution's thumbnail uses the portal that the app is running in, not the portal where the Solution resides. This results in the thumbnail not being found when the item is, say, in production but we're testing in the dev environment.

**Comment by xiao8579** [comment]
Thanks @MikeTschudi!

This issue is a showstopper for us since it affects all the existing templates, for Firefox platform users. Would be much appreciated if it can be fixed soon so we install it for our mid-April release.

**Comment by MikeTschudi** [comment]
Fixed in version 0.22.9

**Comment by xiao8579** [comment]
It's verified on QuickCapture Designer 1.10 devext. All templates can work through Firefox now. Thanks!
