### ISSUE TITLE
Surveys and Content embedded in Experience Builder not added to the dependency list 

### ISSUE THREAD

**Issue by shoe913** [Esri/solution.js#626]
When an Experience Builder application contains embedded content or surveys, all variables are generated correctly but not added as dependencies.  

This causes the deployed experience to have broken links. 

Repro:
1) Create Solution Item from this group: 690fc2ed8a564a48bcfb175c29921b8a
2) Look at dependencies. The following items should be present for the solution to deploy correctly. 

 "b49a3d545c934b93af3753305f3f2a90",
"4ae29cc0278e4c099bc5e7e732ea8d1e",
"ddacaf7d71464f31a425cbcdeb0d1a22",
"3d7abfc1c2024a06ab86bb181bb96491",
"1520ae4c9fc745528039726db7be7455"

**Comment by MikeTschudi** [comment]
Peculiarly, all of the missing items except "b49a3d545c934b93af3753305f3f2a90" (a Web Map) are in the source group.
* 4ae29cc0278e4c099bc5e7e732ea8d1e: Dashboard
* ddacaf7d71464f31a425cbcdeb0d1a22: Dashboard
* 3d7abfc1c2024a06ab86bb181bb96491: Dashboard
* 1520ae4c9fc745528039726db7be7455: Form

**Comment by chris-fox** [comment]
@shoe913, is this still a problem? I don't have a user account in that org to test.

**Comment by MikeTschudi** [comment]
@shoe913, it appears that the test items are gone

**Comment by shoe913** [comment]
@MikeTschudi Sorry about that. I haven't seen this occur in a while, will close for now and reopen as necessary.
