### ISSUE TITLE
\ufeff characters added to Experience Builder text widgets during solution item creation

### ISSUE THREAD

**Issue by shoe913** [Esri/solution.js#627]
When a solution item is created, "\ufeff" is added to text widgets. Upon deployment, this manifests as a question mark character which was not in the original solution.

![image](https://user-images.githubusercontent.com/11777080/116763054-4e309d80-a9d1-11eb-96cc-6026ad9efa43.png)

Repro Item: ef66e0d18aaa409cb1d0692d0229e362
Repro Group: d8ba4aa5f3e044ebaa44dd1dac40dcab

**Comment by shoe913** [comment]
In 5/6 testing of dev branch, "\ufeff" not appearing in item JSON. Still need to verify upon deployment

**Comment by chris-fox** [comment]
@shoe913, could you verify if this is still an issue?

**Comment by shoe913** [comment]
Verified as fixed
