### ISSUE TITLE
Need to resolve organization full url to avoid issues in certain applications

### ISSUE THREAD

**Issue by chris-fox** [Esri/solution.js#63]
For app items the item url is being templatizing as:

**{{organization.portalBaseUrl}}**/apps/CrowdsourcePolling/index.html?appid={{e3e02b6094144ea29741e33e4c7277d8.itemId}}

When I deploy the item it becomes something like:

https://www.arcgis.com/apps/CrowdsourcePolling/index.html?appid=8b9585982bd44c419757bbe2c9a8004c

This is causing issues in some applications when I attempt to configure the application. For example in Crowdsource Polling.

The app url actually needs to be the org urls name:

https://arcgis4localgov2.maps.arcgis.com/apps/CrowdsourcePolling/index.html?appid=8b9585982bd44c419757bbe2c9a8004c

This is the logic I use in python to construct the org url and seems to have worked so far in both online and portal.

    scheme = 'http'
    if 'allSSL' in properties and properties['allSSL']:
        scheme = 'https'
    if 'urlKey' in properties and 'customBaseUrl' in properties:
        org_url = "{0}://{1}.{2}/".format(scheme, properties['urlKey'], properties['customBaseUrl'])
    else:
        url = urlparse(org_url)
        org_url = org_url.replace(url.scheme, scheme)
    return org_url.rstrip('/') + '/'

Before you work on this one, let's decide if we should use a different variable for this or if we want to continue to use the portalBaseUrl variable

**Comment by jmhauck** [comment]
@chris-fox what do you think we should do with the variable? Seems like if nothing else we'd want to move it out of organization.

**Comment by chris-fox** [comment]
@jmhauck, as per our conversation earlier lets move it to the root of the replacement dictionary.

**Comment by chris-fox** [comment]
Verified
