### ISSUE TITLE
Workforce Items no longer appear in item tree

### ISSUE THREAD

**Issue by shoe913** [Esri/solution.js#630]
When creating a solution item with workforce items, the workforce project no longer appears in the item tree. 

Sample Solution Item: https://arcgis4localgov2.maps.arcgis.com/home/item.html?id=07568ae3f6894c1eb564d249ee71f8cc 
Sample Group: https://arcgis4localgov2.maps.arcgis.com/home/group.html?id=eda80b5a07ff4457b515447e0173b7f3#overview

**Comment by MikeMillerGIS** [comment]
@jmhauck would this fix be available in the solutionstest app.  @rtharrington still cannot create a solution from the electric outage.  We are stuck with testing till this is resolved.

**Comment by jmhauck** [comment]
@MikeMillerGIS or @rtharrington could I have a link to the item? Also what app? I tested with the deploySolution demo app from this repo but could take a look at whatever app you are using.

**Comment by MikeMillerGIS** [comment]
User: jhauck_arcgissolutions 
Group: https://arcgissolutions.maps.arcgis.com/home/group.html?id=7b77116d00824b6f923e5a456a30030a#overview

Create a solution from this group, the content do not show from the resulting item.

@rtharrington what was the link to the app used to create the solution

**Comment by jmhauck** [comment]
Thanks...I'll take a look. And my bad...I said deploy but the fix was on the create side.

**Comment by rtharrington** [comment]
> Thanks...I'll take a look. And my bad...I said deploy but the fix was on the create side.

FYI...When I created the solution, the solution items doesn't list any of the content like it usually does. 

![image](https://user-images.githubusercontent.com/25378341/118685186-dfc14d00-b7d0-11eb-97d3-8018035bcff5.png)

**Comment by jmhauck** [comment]
@rtharrington what was the link to the app used to create the solution? I am seeing content listed when I use the createSolution demo app from this repo.

![image](https://user-images.githubusercontent.com/2170893/118687675-8520f480-b7c2-11eb-8e35-a7b562ef83d2.png)

**Comment by rtharrington** [comment]
> @rtharrington what was the link to the app used to create the solution? I am seeing content listed when I use the createSolution demo app from this repo.
> 
> ![image](https://user-images.githubusercontent.com/2170893/118687675-8520f480-b7c2-11eb-8e35-a7b562ef83d2.png)

I used https://solutionstest.esri.com/create/index.html?sortField=modified&sortOrder=desc#create

**Comment by jmhauck** [comment]
@rtharrington that app was still based on the release branch but is now rebuilt from develop. Could you give it a go now?

**Comment by rtharrington** [comment]
> @rtharrington that app was still based on the release branch but is now rebuilt from develop. Could you give it a go now?

It worked for creating it with the content but I'm still not able to deploy it. 
using this site to deploy it. https://solutionstest.esri.com/online-test/index.html?sortField=created&sortOrder=desc#solutions

![image](https://user-images.githubusercontent.com/25378341/118698584-94ae3680-b7de-11eb-914a-4a9d0c6f5a85.png)

**Comment by jmhauck** [comment]
@rtharrington this looks like a broad issue that @shoe913 is tracking with core. Will mention here as soon as I know more.

**Comment by shoe913** [comment]
Verified
