### ISSUE TITLE
Remove layer updateDefinition calls for Feature Services deployed to ArcGIS Online

### ISSUE THREAD

**Issue by chris-fox** [Esri/solution.js#644]
With the move to async calls for addToDefinition and updateDefinition we are seeing a significant decrease in performance of deployment. 

According to the dev team we should be able to define a layer completely with the original addToDefinition request w/o needing to call updateDefinition afterwards to set properties. This is not the case currently with some properties, but we have reported to the dev team and they plan on addressing.

So in preparation I would like to update our logic to remove any need to call updateDefintion on a layer during deployment. These are the properties I am aware of that we currently set via updateDefinition:

templates, types, drawinginfo, typeIdField, fields, and viewDefinitionQuery

We should update to pass all these properties in the layer/table definition in addToDefinition and remove calls to updateDefinition.

We probably need to keep this updateDefinition logic for now for Enterprise, but I will work with the Enterprise team to see if they can also work towards the same goal of not requiring subsequent updateDefinition calls.

**Comment by chris-fox** [comment]
@jmhauck, in devext we can now update the templates, types, typeIdField, fields and viewDefinitionQuery in the original addToDefinition request.

For fields if the domain or field alias are different from the source service we also need to pass “isViewOverride”:true on the field. I believe we already checking if the domain is different from the source as part of the updateDefinition logic and only passing those fields. This would be a slight change from that logic to discover fields that have a different domain or field alias and add the “isViewOverride”:true property to the field in the original addToDefinition request.

I am still asking Khaled about the "visible":false property as IMO we shouldn't have to set the “isViewOverride”:true property. Will confirm on this.

**Comment by jmhauck** [comment]
@chris-fox any special considerations for portal vs online?

**Comment by chris-fox** [comment]
I will do some testing in Enterprise to see if we need to have separate logic. If there are limitations in Enterprise I will log issues with the enterprise team.

**Comment by chris-fox** [comment]
@jmhauck, Khaled has resolved the remaining issue I am aware of in DevEXT. For field visibility we shouldn't need to do anything special in addToDefinition, we can just pass "visible": true/false and this setting will persist. So the only special case we need to handle now is if the field alias or domain is different than the source, we need to add "isViewOverride":true to those fields.

**Comment by chris-fox** [comment]
Verified
