### ISSUE TITLE
Delete protect Solution item

### ISSUE THREAD

**Issue by chris-fox** [Esri/solution.js#657]
Now that we support deleting a solution, would like to delete protect the Solution item when a Solution is deployed. As we rely on the Solution item more in the workflow this helps prevent unintentionally deleting of the Solution item.

**Comment by dbouwman** [comment]
@chris-fox please let me know when this gets folded in, as Hub deletes the Solution item when we create things from "embedded templates", and we will need to account for the Solution item being protected.

**Comment by chris-fox** [comment]
@dbouwman, we just implemented this in #669.

**Comment by chris-fox** [comment]
Verified

**Comment by chris-fox** [comment]
@MikeTschudi, I found during testing if a solution failed to deploy the solution item was not cleaned up during the deleting. I am guessing because it was delete protected. Could we unprotect the solution item and delete during a failure?

**Comment by chris-fox** [comment]
Verified
