### ISSUE TITLE
Images embedded in ExB are not picked up as resources when a Solution Item is created

### ISSUE THREAD

**Issue by shoe913** [Esri/solution.js#659]
Some images embedded in an experience are not captured as resources or dependencies. 

1) Create a solution from group: 9880c8b8ef6d43c2bf5d071875a853e3
2) Due to #652 , remove line 10354 (this should reference 9ed54debbb0448f1871b45e5b7cb19f0 as a dependency)
3) Deploy the solution 
4) On the Solutions ExB (Damage Assessment Operations) go to the Administer Tab

Bug: All the images are missing. In the JSON of the Template, the part of the URL for the image is swizzled. However the image is not captured as a resource or listed as a dependency

![image](https://user-images.githubusercontent.com/11777080/121395265-15a4ad80-c907-11eb-81fe-73e30635d1c6.png)

![image](https://user-images.githubusercontent.com/11777080/121395213-07569180-c907-11eb-9e67-b74bd7f1f8dc.png)

**Comment by chris-fox** [comment]
@shoe913, when I tried to deploy it failed creating a WAB item. I think there is an issue with packaging the resources. The items have a lot of resources. Do you still have the solution item you used to repro this? Wondering if we can check if the resources are missing.

**Comment by MikeTschudi** [comment]
If there are more than 50 resources in the original item, some will be lost due to AGO's 50-files-per-zip max. (See https://github.com/Esri/solution.js/issues/616#issuecomment-856179458.)

**Comment by chris-fox** [comment]
In my version of the item I created I see the resource listed in the resources, and the image is stored in the solution item resources

![image](https://user-images.githubusercontent.com/6796763/121401043-49430000-c926-11eb-8213-e256a0b206d9.png)

![image](https://user-images.githubusercontent.com/6796763/121402660-29144080-c928-11eb-91e5-6898a12edd8e.png)

**Comment by shoe913** [comment]
@chris-fox @MikeTschudi 

I repro'd with this item: https://localdeployment.maps.arcgis.com/home/item.html?id=3d20cdb7f71b4648918d647bc6bc3f82

According to ArcGIS Assistant, there are 131 resources (plus however many are missing) for the solution item. There are 14 on the original ExB.

**Comment by shoe913** [comment]
@chris-fox Testing again now from develop. I've also seen this occur recently with WAB apps containing the Info Summary Widget -- I hadn't narrowed those tests down yet as the creation method was using https://solutionstest.esri.com/create/index.html several days ago.

**Comment by chris-fox** [comment]
No longer reproducible.
