### ISSUE TITLE
Add Support for Groups

### ISSUE THREAD

**Issue by chris-fox** [Esri/solution.js#66]
Need to support templatizing and deploying groups. Specifically we are using them for Web Mapping Application group templates like Crowdsource Reporter and Crowdsource Manager and for Workforce projects.

**Comment by chris-fox** [comment]
After deployment and creation of the groups we need to share the new items previously shared with the group with the new group.

**Comment by jmhauck** [comment]
@chris-fox do you see a particular example of this not working? The first one I tried was d915488a197e4c7eb7186c6650c65e17 from the localdeployment org. It looks like only the map was shared with the group and on deployment I see the map being shared with the newly created group. 

Also looks like the solution item display isn't correct as I only see the application listed and nothing else. Seperate issue but something I noticed while testing it.

**Comment by chris-fox** [comment]
@jmhauck, yes it does appear to be sharing the items with the groups properly. The citizen problem reporter item in the Deploy Solution gallery shows a more advanced case as it has 8 web maps shared with the group. That aspect is working well.

The issues I am seeing that I would like to address as part of this issue to call it complete:

1. Fix how the dependencies are listed in the template and deployed items for groups.
2. When we deploy a group the thumbnail of the group is not being set as was defined in the original item.
3. For the name of the group we should try to use the original name of the group defined in the template. If a group with that name already exists we should add a 1,2,3 etc to the name similar to how we are naming folders. For example:

Citizen Problem Reporter
Citizen Problem Reporter 1
Citizen Problem Reporter 2

**Comment by jmhauck** [comment]
@chris-fox in regards to the dependecy issue...at one point we added logic to filter out any items that are referenced in a solution item but no longer exist. To verify if an item exists I added a search call to look for the referenced itemIds but it only searchs items and not groups. WIll need to add a group search as well.

**Comment by jmhauck** [comment]
The fix for the dependecy issue was merged last night. Not sure of the timing but I'd think it will be in devext today. Will check a little later on in the day.

**Comment by chris-fox** [comment]
That's great @jmhauck, thanks for the quick follow-up on this.

**Comment by jmhauck** [comment]
The fix is on devext.

**Comment by shoe913** [comment]
Verified, name changes as needed, group icon comes through, and group  dependencies show up (in logical manner) for solution item. 

Link for items is incorrect. This is not specific for solutions with groups.  See 170 for more information .
