### ISSUE TITLE
Exclude /config/config.json resource from Web Experiences during creation

### ISSUE THREAD

**Issue by chris-fox** [Esri/solution.js#660]
This seems to be a regression, I am guessing related to this change: #628.

The config/config.json is used in Experience Builder to store the draft for the app. When you publish the changes they are pushed to the data of the item.

The Web Experience already has logic to create a config/config.json resource using a copy of the item's data during deployment. This important because all paths are properly swizzled in the item data keeping the draft and published version in sync. 

The issue here is because we are packaging the original items draft config as a resource, we are overwriting this updated config with the old version in a subsequent addResources request. So when you go to edit the resulting web experience using the draft none of the paths have been swizzled, they point to the original paths,

![image](https://user-images.githubusercontent.com/6796763/121706188-6224f000-caa3-11eb-9187-e56a1e5ac5ad.png)

**Comment by MikeTschudi** [comment]
@chris-fox, a version of the repo also does not store any ExB resource that starts with "images/". Are you familiar with these?

**Comment by chris-fox** [comment]
@MikeTschudi, we should keep anything in the images folder, this folder keeps any images that were uploaded in the experience. The only resource i know of that we don't want to keep is the config.json.

**Comment by chris-fox** [comment]
Verified
