### ISSUE TITLE
Add Support for Web Scene item type

### ISSUE THREAD

**Issue by chris-fox** [Esri/solution.js#673]
Looking at the JSON I believe we can handle exactly the same as a web map item type. When creating the solution from a web scene we should iterate over the operational layers and look for hosted feature layers using the same logic as web map and add them as dependencies. 

I would also like to look into handling hosted scene layers, I will log a separate issue for this.

In addition, similar to a recent change in the web map we should omit the property initialState from the solution template.

Here is a sample web scene and group to test with:

Web Scene: d7e5d2c515194b148ee433aa779a699e
Group: b33c9766b6f24abca162807e11d9114d

**Comment by shoe913** [comment]
Verified
