### ISSUE TITLE
Add support for Velocity Real time and Big Data Analytic item types

### ISSUE THREAD

**Issue by chris-fox** [Esri/solution.js#674]
Velocity has there own api for reading, creating and deleting analytics. You can see their api documentation here for our localdeployment org:

https://us-iot.arcgis.com/usadvanced00/pipftfmrv9d1divn/iot/api/swagger.html#/BigData_Analytics

This portion of the url will change depending on the organization:

https://us-iot.arcgis.com/usadvanced00/pipftfmrv9d1divn/

You can get this information from the org by requesting the subscriptionInfo on the portal, and it will return something like below if Velocity is enabled where you can get the velocityUrl

https://www.arcgis.com/sharing/rest/portals/self/subscriptionInfo
"orgCapabilities": [{
	"id": "velocity",
	"test": false,
	"level": "Advanced",
	"region": "US",
	"status": "active",
	"endDate": 1632700800000,
	"itemUnits": 0,
	"computeUnits": 0,
	"velocityUrl": "https://us-iot.arcgis.com/usadvanced00/pipftfmrv9d1divn",
	"storageUnits": 0
}
]

We can then use their api to request the json for the real-time and big-data analytics and store that with the template's data. During deployment we can use the api to create a new real-time or big-data analytic using the json defined in the template.

Analytics can point to hosted feature layers in the portal and they are referenced by their item id's. For example here is an example analytic, it has a sources property. I don't feel strongly that we need to add logic to automatically discover these dependencies, if we could use the logic we use for ExB for example where we automatically find item id references that are shared with the same group during creation and replace the item id references with a variable I believe that would work.

	"sources": [{
			"id": "7afde56d-646e-75cc-a53e-4613cc34d359",
			"name": "feature-layer",
			"label": "Snow Routes",
			"schemaTransformation": {..},
			"properties": {
				"feature-layer.portalItemId": "0d6893904c4d4191b5c2312e60e8def7",
				"feature-layer.outSR": "4326",
				"ui": {
					"top": 10,
					"left": 10,
					"width": 240,
					"height": 70
				}
			}
		}

Below are 2 item ids that can be used to test with:

Real Time Analytic: a728f0cf8bdc4fb19749cc1cbad1651b
Big Data Analytic: beeebfe193554397b088e570a47c735a

**Comment by jmhauck** [comment]
@chris-fox what about feeds?

**Comment by chris-fox** [comment]
@jmhauck, let's add support for feeds as well. Thanks.

**Comment by jmhauck** [comment]
@chris-fox the FS view a5dbdbad24534af487b53c0515b003ee from a728f0cf8bdc4fb19749cc1cbad1651b has itself listed under its sources.

https://services7.arcgis.com/piPfTFmrV9d1DIvN/arcgis/rest/services/Active_Snowplow_Driver/FeatureServer/sources?token=...

This is causing a failure further downstream. Is this cyclical dependency expected for some reason?

**Comment by chris-fox** [comment]
@jmhauck Yes, that is expected it is a custom kind of view that is supported in the platform. You made some changes to support this in the issue below. Is this no longer working?

https://github.com/Esri/solution.js/issues/587

**Comment by jmhauck** [comment]
@chris-fox thanks...I didn't remember this. Its hitting an issue with how the fields are managed but recalling this definitely helps me know what to do.

**Comment by jmhauck** [comment]
@chris-fox when deploying from beeebfe193554397b088e570a47c735a I am seeing an error on addToDef about duplicate geometry def that I don't fully understand yet. Only way I've dealt with it thus far is to modify the solution data manually before deploy.

**Comment by jmhauck** [comment]
Still need to revisit the issue mentioned above about the addToDef call but the main parts of velocity support are hopefully there.

**Comment by chris-fox** [comment]
@jmhauck, the issue is it is failing on Velocity feature layers. These feature layers are created in the spatiotemporal datastore for Velocity and are different from the hosted feature layers in ArcGIS Online. We can't create these items through deployment and should skip them. I am putting together slide deck to discuss this and will setup a meeting next week to discuss.

**Comment by chris-fox** [comment]
@jmhauck, per our meeting attached is the slide deck describing the changes I would like to make to the logic to handle our inability to create Velocity feature layers during deployment. 

[Updates.pptx](https://github.com/Esri/solution.js/files/6955580/Updates.pptx)

**Comment by jmhauck** [comment]
@chris-fox I didn't see a Map Service issue with the items from the group 33660dca16c3431a8ac1d4a4e13946c1 

The only thing I did in regards to Map Service was remove mapServicePortalItemID from outputs.

**Comment by jmhauck** [comment]
@chris-fox while testing with the solution from above (e3ac5) I am seeing an item id and url that are not being replaced in a webmap (ea8768807a954af1b661078a2c1575cf) on deploy. When I look through the templates in this item from create the service template does not have the layer at id 0. When I go back and run create on that webmap I do see that the service does have a layer at id 0 so I'm not exactly sure what happened when the above was created or if maybe the service has changed but if you see any issue while looking at it please let me know.

**Comment by chris-fox** [comment]
@jmhauck, i think this is ok, we did make some changes to remove a layer from a service to refactor. We aren't using that solution item anymore for release.

**Comment by chris-fox** [comment]
verified
