### ISSUE TITLE
Delete on failure is not successfully removing all items created during deployment

### ISSUE THREAD

**Issue by chris-fox** [Esri/solution.js#675]
Deploy this item, it will fail near the end of deployment and attempt to cleanup but at the end there are still items remaining in the folder. I am not sure if its the order, but it seems to attempt to failing deleting feature services because views on top of the service still exist.

ef64dd757233443ba84c135b8e51bcbf

**Comment by MikeTschudi** [comment]
Not able to reproduce on the release/ago-9.2 branch. Updating the develop branch with the delete-solution updates (to unprotect Solution item) . We have some instability with the builds on the test server.

**Comment by MikeTschudi** [comment]
On 9.2 branch, solution deploys
On develop branch, solution fails to deploy but fully cleans up after itself

**Comment by chris-fox** [comment]
@MikeTschudi, i updated the item to make it fail on the hub site at the end of the deployment. I find the result isn't consistent. Sometimes it cleans up everything, however occasionally the folder and some services remain after it attempts to delete everything. It is not consistent and the same services are not left behind each time.

**Comment by MikeTschudi** [comment]
Thank you, @chris-fox, for the update and additional info.

**Comment by MikeTschudi** [comment]
Got it:
```json
{"error":{"code":400,"messageCode":"CONT_00481","message":"Unable to delete item. This service item has a related Service item","details":[]}}
```
for a Feature Layer (hosted). Can be deleted manually afterwards.

**Comment by chris-fox** [comment]
Verified
