### ISSUE TITLE
Hub Site Application loses its title when put into a Solution

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/solution.js#687]
HSA 809404b50ccb423b8557f3d9c7cadcbc has the title "Emergency Response", but when it is put into a Solution, its `item.title` and `data.title` properties have the value "{{solution.title}}".

The title returns when the Solution is deployed.

This problem exists as far back as v0.16.9 with this item.

**Comment by chris-fox** [comment]
I believe this intended behavior as the Hub app supports renaming the solution when activated. So they want to use the variable so that the site gets the new name when activated. In most of our solutions we just go in and change it from this variable to the name we want to pass when deployed.

**Comment by chris-fox** [comment]
Yes, we should discuss with the Hub team. 

@dbouwman, what do you think? We always have to go in an remove the {{solution.title}} variable and replace with the hardcoded name for the site. Anyway we could support our different use cases between solutions and Hub?

**Comment by MikeTschudi** [comment]
If Hub uses `convertSiteToTemplate` from `@esri/hub-sites` to templatize a Hub site rather than `convertItemToTemplate` from `@esri/solution-hub-types`, then we can solve this with some post-processing in the latter.

**Comment by chris-fox** [comment]
this was resolved.
