### ISSUE TITLE
Feature Service Object ID field is being created with a non-unique index

### ISSUE THREAD

**Issue by chris-fox** [Esri/solution.js#69]
I have the same issue in my python code, but when I create the feature service using the templates in Online it is created successfully with a unique index. Having a unique index is important in some workflows, for example when appending data through the item details can fail if there is no unique field index.

We should work with the hosted feature service team to understand how we pass the field definition to ensure the object id is created with a unique index.

**Comment by jmhauck** [comment]
Just wanted to add a note here. The fix for this was from core and is only on Devext at this point.

**Comment by chris-fox** [comment]
Verified on Devext
