### ISSUE TITLE
Circular dependencies prevent item tree from displaying

### ISSUE THREAD

**Issue by shoe913** [Esri/solution.js#713]
Possibly related to #652 

Item: https://localdeployment.maps.arcgis.com/home/item.html?id=76e27367a2ab40b59952ce7361a89cb2
Group: https://localdeployment.maps.arcgis.com/home/group.html?id=00b092991d6e4e27acb6399eae88fa4a

The item tree does not appear in the solution item above. This is caused by a cyclical dependency in the experience. 

The Experience has a dashboard which has a html link to the experience. All dependencies are listed correctly on the items, however the display fails to render on the item details page.

**Comment by MikeTschudi** [comment]
Failure appears to be in creation of solution; 76e27367a2ab40b59952ce7361a89cb2's data:
```json
{
  "metadata": {},
  "templates": []
}
```

**Comment by chris-fox** [comment]
@MikeTschudi, yes I think that is the best option we have in this situation.

**Comment by MikeTschudi** [comment]
AGO fix in arcgis-portal-app PR 37154

**Comment by shoe913** [comment]
Verified
