### ISSUE TITLE
In Enterprise, relationship ID in a feature does not match the solution definition. 

### ISSUE THREAD

**Issue by shoe913** [Esri/solution.js#724]
The relationship ID on Feature Services laid down with deployment does not get the same ID as defined in the solution item. This causes issues with widgets that expect the relate (ex. Smart Editor). 

Steps to repro
1) Electric Distribution Data Management to ArcGIS Enterprise
2) Go to the rest endpoint of the Electric Distribution System service and view the "Poles" layer (example: https://rpubs19021.ags.esri.com/server/rest/services/Hosted/ElectricDistributionSystem_e81454466a0f490f9da07488216c14a8/FeatureServer/900121)
3) Note the relationship listed has ID number 4 and 0
4) Look at the JSON for the service in the solution-items repo
5) Note the relationship states the should be ID 2 and 3

**Comment by jmhauck** [comment]
@chris-fox not sure what to do about this one. The related table ids remain as they should but the relationship ids in the result are not what we pass in and I get an error when I make an additional updateDef call to try and set them after. Do you know of anything that would preserve the relationship ids?

**Comment by chris-fox** [comment]
@jmhauck, this may be a limitation in Enterprise. @shoe913, wondering if we could change the id's in the original services to match what is created in Enterprise and then update the smart editor configs to reflect the new ids. We should probably be safe to do this in Online as well.

At the same time I can add this to the list of fixes to ask the Enterprise team for.

**Comment by chris-fox** [comment]
Verified

**Comment by chris-fox** [comment]
Preserving relationship IDs was implemented in 12.1
