### ISSUE TITLE
Solution failing to deploy with Console error in createItemWithData

### ISSUE THREAD

**Issue by chris-fox** [Esri/solution.js#73]
@jmhauck I just encountered this one. I see it when attempting to deploy Election Outreach, the console error happens relatively quickly and it keeps good for a little bit but then just stops and doesn't complete the deployment.

![image](https://user-images.githubusercontent.com/6796763/61905518-4c31d480-aef7-11e9-808e-e50f2ec0ef57.png)

**Comment by jmhauck** [comment]
@MikeTschudi please check this commit out. Not sure if you had another thought for this and why copyFilesToStorageItem was returning a boolean. I switched it to return a string array of the resource names. Also changed generateStorageFilePaths to specifically check if it's defined and has the map function . In the cases where boolean true was returned for resources it could get past the upfront assertion:

`template!.resources || []`

**Comment by MikeTschudi** [comment]
@JMHauck  I didn't have a need for the names yet, so took the simpler route. But we'll want them for status reporting and error recovery, so thank you for the changes.

**Comment by chris-fox** [comment]
Verified
