### ISSUE TITLE
Time enablement is lost on view layer if source doesn't have time enabled

### ISSUE THREAD

**Issue by shoe913** [Esri/solution.js#731]
ArcGIS Online allows views to have time enabled without the source having time enabled. 

When a solution item contains a view with time enabled, if the view's source layer doesn't also have time enabled, none of the deployed content will have time enabled. 

Test Item: 
https://localdeployment.maps.arcgis.com/home/item.html?id=32a69ff67bb6434a8db6e88564ef5be2#settings

**Comment by chris-fox** [comment]
I e-mailed the dev team about this, asking that they honor timeInfo in the addToDefinition request for views.

**Comment by chris-fox** [comment]
This has been resolved in devext and will be available in the 9.4 release.
