### ISSUE TITLE
QuickCapture: OIC item's serviceURL property is not correct after deploy a template by connecting to Enterprise portal

### ISSUE THREAD

**Issue by xiao8579** [Esri/solution.js#750]
**Describe the bug**
When deploying the Esri template that has the new OIC serviceURL pattern, if a user has been connecting to Enterprise portal from the QuickCapture AGO site. The `serviceURL` has www.arcgis.com as the portal, but it should use the Enterprise portal.

**To Reproduce**
1. Go to https://devext.arcgis.com/apps/quickcapture
2. Sign in with ArcGIS Enterprise https://rpubs19020.ags.esri.com/portal (creator1 | portalaccount1)
3. New template > Windshield Damange Assessment > Use
4. In the deployed OIC item, check its item `data`, the portal url is www.arcgis.com
"ServiceURL": "https://www.arcgis.com/home/item.html?id=02a7c44e3f504a20a4c9f37b6c91e213&sublayer=0"

**Expected behavior**
In the deployed OIC item, check its item `data`, the portal url should be https://rpubs19020.ags.esri.com/portal
"ServiceURL": "https://rpubs19020.ags.esri.com/portal/home/item.html?id=02a7c44e3f504a20a4c9f37b6c91e213&sublayer=0"

**Comment by xiao8579** [comment]
This is a high priority for the QuickCapture team. We worked with the Oriented Imagery team to come up with new URL pattern for the `serviceURL` property for the OIC item, and needs it to work properly for both Online and Enterprise environment. We target to release this with Online 9.4, and all our existing templates created by the Solution need to update too with this new pattern. @MikeTschudi Would you mind taking a look?

**Comment by chris-fox** [comment]
@xiao8579, you can fix this now in your Solution item if you edit the json and replace "https://www.arcgis.com" with {{portalBaseUrl}}. So for example instead of : 

"https://www.arcgis.com/home/item.html?id=02a7c44e3f504a20a4c9f37b6c91e213&sublayer=0"

Update to:

"{{portalBaseUrl}}/home/item.html?id=02a7c44e3f504a20a4c9f37b6c91e213&sublayer=0"

This variable will be replaced when deployed with the portal url. So it will work for Online and Enteprrise.

**Comment by xiao8579** [comment]
@chris-fox Thanks, I will give it a go. 👍

**Comment by xiao8579** [comment]
I can do the fix for this release, but are there any plans to fix it in solution.js? The new pattern for the OIC item's serviceURL that we have come up with is, e.g. https://www.arcgis.com/home/item.html?id=&sublayer=0

**Comment by chris-fox** [comment]
We need to add some additional logic for OIC items to templatize this property automatically, but if the serviceURL is a hosted feature layer or view we should be able to do this during the solution creation.

**Comment by chris-fox** [comment]
@xiao8579, this should be resolved in the Create app. We will find this reference and properly replace with variables that we had you manually change.
