### ISSUE TITLE
URL parameter is added to web maps upon solution item creation

### ISSUE THREAD

**Issue by shoe913** [Esri/solution.js#761]
Adding the URL parameter to web maps during item creation prevents them from being downloaded and updated in ArcGIS Pro. 

During creation, we need to ensure that the URL property on for web maps is set to null.

**Comment by chris-fox** [comment]
I would amend and say, if the url is null we should keep it as null, if there is a url in the original web map than we should handle it like we do other urls. I am not sure all the scenarios, I think the idea is we should not be changing it from what it was originally set as.

**Comment by jmhauck** [comment]
@shoe913 could I see an example where this happens? I see the spot in the code where we set this but have not been able to reproduce the issue at this point. I tried with maps that I created or after looking at a few maps from the first couple of solutions I tried after deploying.

**Comment by shoe913** [comment]
@jmhauck I'm still seeing this with the demo app. 

If you deploy the Electric Underground Inspections solution (f6b16af72e1d42cfb371b3d5665df947), the Underground Inspections map is still getting a URL added in the JSON. 

The original content has a value of null for this parameter.

**Comment by chris-fox** [comment]
@shoe913, I don't believe this fix should fix already authored solution items with this url property. We should check that this url property is not set in newly authored solution items via the creation app.

For items in our repro that already have this problem, we should fix in the repo for the next release.

**Comment by shoe913** [comment]
Solution items in the solution item repo have been fixed with this [PR](https://devtopia.esri.com/WebGIS/solution-items/commit/7cb74315220faabc7df7f81ef72f48c4d0792063) 

I used the demo apps to create a new solution item from this group: df635643771a4418810efbdf69ad3272 
The following solution item was created: https://localdeployment.maps.arcgis.com/home/item.html?id=dbfb695ec3a14c9eb1e0b4759266f5fb

Looking at map 1ce51b0c4de84ade86ccc20bdb032258 (Curbside Service Schedules) in the original and then the deployed content, I see the following:
- The URL property is on the original map and then transposed into the solution item and deployed content. 
- For both the deployed and original, the map cannot be opened and updated in ArcGIS Pro. 

I'm not sure how the URL property was added to the original map ( I didn't do it manually) or what it is responsible for. The ArcGIS Pro team has addressed this issue on their end (issues 2893) to ignore the url property. 

However I think our solutions should be standardized in what they have in this parameter. We should either undo- the above PR in the solution items repo to keep the url property filled or, set all new solutions to have the URL property as null in web maps. 

@chris-fox , which way do you think we should pivot on this.

**Comment by chris-fox** [comment]
Since we don't know how this property is used or how it was added to the original map, I don't think we should be setting it to null when we create the solution item. We don't know the ramifications of how it was used by whatever was used to author it. As you mentioned the Pro has fixed their bug so that doesn't seem to be a problem anymore. 

I like the behavior of John's PR, we templatize the property if it is specified, otherwise we leave it null if the original map is null. This ensures the deployed item matches the original item much like how we treat everything else. Unless we get clear feedback from the dev team that this url property should always be null for web maps, I am inclined to not mess with the original web map specifies.

**Comment by shoe913** [comment]
Verified
