### ISSUE TITLE
Some Notebooks failing to templatize

### ISSUE THREAD

**Issue by chris-fox** [Esri/solution.js#763]
Attempt to create a solution using the following item: 8d33119f52264ea8b13ed01949ffb2a6

It will fail with the error:

One or more items cannot be converted into templates
e06554ef6dede6cf37eb5b8b184b402c
dbb4d0879a3a46ab8c8d5ae873d1a9d9
58ef03d31bd44172bad4a994c210b82a
54f192c78007463eba6c22a86194529f

If you download the notebook and open it and notepad you can see a couple issues:

- There is an interpreter property with a hash that is being treated like 2 item ids.	
                ```"interpreter": {
			"hash": "e06554ef6dede6cf37eb5b8b184b402cdbb4d0879a3a46ab8c8d5ae873d1a9d9"
		},```

- There is a papermill property that has a couple other references to some guids that aren't actually item ids.

		"papermill": {
			"default_parameters": {},
			"duration": 124.868927,
			"end_time": "2021-12-19T11:03:32.296659",
			"environment_variables": {},
			"exception": null,
			"input_path": "/arcgis/home/.tasks/58ef03d31bd44172bad4a994c210b82a/54f192c78007463eba6c22a86194529f.ipynb",
			"output_path": "/arcgis/home/.tasks/58ef03d31bd44172bad4a994c210b82a/output.ipynb",
			"parameters": {},
			"start_time": "2021-12-19T11:01:27.427732",
			"version": "2.3.3"
		}

The papermill property is added when you schedule the notebook to run as a task. I am not sure when the interpreter property is added, but it is not needed in the notebook.

Could we remove both the papermill and interpreter properties during templating?

**Comment by jmhauck** [comment]
@chris-fox this removes the props from the metadata at the root and in cells specifically. Could make it more generic if they could show up in other places.

**Comment by chris-fox** [comment]
Thanks @jmhauck, I am not aware of any other places so this is good.

**Comment by chris-fox** [comment]
verified
