### ISSUE TITLE
Update logic for Groups source-xxxx tag to use typeKeywords instead

### ISSUE THREAD

**Issue by chris-fox** [Esri/solution.js#765]
When we create an item we write a typeKeyword to the item so we know what original item it came from so that it can be reused by solutions that share the same items. For group we have be writing this as a tag, because the typeKeyword wasn't previously supported.

It now is and we can write this typeKeyword to the group instead, which is better because users can't see or modify tags through the UI. Let's update the logic for groups to use typeKeywords instead.

For the searching on reuse we need to search both tags and typeKeywords to support previously deployed versions of the group. We should be able to do this as an Or in the query.

**Comment by shoe913** [comment]
Verified
