### ISSUE TITLE
Populate the "notes" columns in the documentation

### ISSUE THREAD

**Issue by philnagel** [Esri/solution.js#802]
I'm referring to the [API reference](https://esri.github.io/solution.js/api/). For example, when looking at the docs for [`IDeploySolutionOptions`](https://esri.github.io/solution.js/api/common/IDeploySolutionOptions/), there is nothing populated in the Notes column. However, there are some notes present in the comments in the code. Would it be possible to transfer those into the notes column at least to have some more guidance on the effect of parameters?

screenshot from the reference with empty Notes column:
![image](https://user-images.githubusercontent.com/17130646/164085031-ba8bbb75-290e-4222-9b8e-78606043a6ca.png)

screenshot from corresponding section in the code:
![image](https://user-images.githubusercontent.com/17130646/164085200-51f22914-4c3d-4c2a-b605-8dc87ed6ba10.png)

**Comment by MikeTschudi** [comment]
Thank you, Phil. Here's IDeploySolutionOptions in the revamped docs:  https://esri.github.io/solution.js/interfaces/common.IDeploySolutionOptions.html
