### ISSUE TITLE
Add support for Contingent Values in feature services

### ISSUE THREAD

**Issue by chris-fox** [Esri/solution.js#816]
Field Maps and the Map Viewer Editor recently added support for Contingent Values and these can be created and persisted in hosted feature services. After working with the Online team the process would be:

During solution creation
1. Determine if a layer in a service has contingent values by checking for a property "hasContingentValuesDefinition" : true on the layer or table.
2. Query the contingent values for each layer. You can get this info from the endpoint <feature-layer-url>/contingentValues?f=json
3. The object returned will look like:
` {
"typeCodes": [....],
"stringDicts": [....],
"contingentValuesDefinition": {...}
}`
4. We don't need to persist the "typeCodes" property, this is universal and doesn't need to be passed in when adding to a new layer. For the stringDicts, we should persist this inside the first contingentValuesDefinition.fieldGroups object. This is required when adding to a new layer and there will always be at least on fieldGroup in the contingentValuesDefinition. We should also drop the properties,  "layerID", "layerName", "geometryType" and "hasSubType" properties on the contingentValuesDefinition object.

During solution deployment
1. We can't pass the contingentValuesDefinition in the original addToDefinition request where we add the layers and tables. I asked about this and unfortunately it was too challenging to implement this in a single add operation. So we need to strip this information out of the initial request.
2. For any layers that had a contingentValueDefinition, we would then need to do another addToDefinition request on each layer and pass the contingentValueDefinition.

This functionality is currently only working in DevEXT. We can test this behavior in DevEXT and will be available in the next AGOL release. You can use this sample feature service to test this behavior: 6e6cae8c35a44589a6062585a22ab19e

In addition, attached are 2 json files defining the definition we should persist in the solution item for layer0 and layer1 in the example above, and the json that we would pass in the addToDefinition of each layer during deployment.

[JSON-examples.zip](https://github.com/Esri/solution.js/files/8711658/JSON-examples.zip)

Contingent Values are not currently supported in Enterprise hosted services, so this will only apply in ArcGIS Online

**Comment by chris-fox** [comment]
@jmhauck, I confirmed that this doesn't apply to views. Views will return contingent values, but they just honor the definition in the source service, so we shouldn't get or add CVs from Views, just the source services.

**Comment by jmhauck** [comment]
@chris-fox its in now

**Comment by chris-fox** [comment]
Verified
