### ISSUE TITLE
Solution Contents on Info Page are not aligned

### ISSUE THREAD

**Issue by shoe913** [Esri/solution.js#828]
Currently on DevEXT, the solution contents icons are not aligned with the text. 

Looks like the spacing on the icons may have changed

![image](https://user-images.githubusercontent.com/11777080/181104415-e7d22ae3-e8c8-43fe-a388-a45d8f824843.png)

**Comment by jmhauck** [comment]
just submitted a PR for this and tagged you

**Comment by shoe913** [comment]
Verified
