### ISSUE TITLE
Need to templatize Ops Dashboard dataset references

### ISSUE THREAD

**Issue by chris-fox** [Esri/solution.js#86]
Operations Dashboard allows you to reference data sources outside the web map as standalone sources. We need to templatize these during the solution creation as well.

A datasource reference will look like below and can be found in the Widgets collections as well as the selectors within the Header or Left Panel.
                                    "dataSource": {
                                        "type": "featureServiceDataSource",
                                        "itemId": "e6f6f748903e4528b004b7c2e4136073",
                                        "layerId": 0,
                                        "table": false
                                    },

Below is the current python code showing how these datasources are found

The Election Results solution has an example where a datasource to a feature service is specified. We should only be templatizing featureServiceDataSources that have an itemId, i.e hosted.

In terms of listing the dependencies. I would like to see the feature service as a dependency of the dashboard only if it is not also a dependency of a web map also referenced in the dashboard. For example in Election Results the feature service is also used in one of the web maps, So I don't think we should list it as a dependency of both the dashboard and the web map.

```
        if 'widgets' in self.data:
            for widget in app_json['widgets']:
                if widget['type'] == 'mapWidget':
                    if 'itemId' in widget:
                        widget['itemId'] = clone_mapping['Item IDs'][widget['itemId']]
                elif "datasets" in widget:
                    for dataset in widget["datasets"]:
                        if "dataSource" in dataset and "itemId" in dataset["dataSource"]:
                            # in some cases the layer ids may have changed when cloning
                            # so we can use a mapping between the old and new to update it
                            for url, cloned_service in clone_mapping['Services'].items():
                                if cloned_service['id'] == clone_mapping['Item IDs'][dataset["dataSource"]["itemId"]]:
                                    # update the layer id
                                    dataset["dataSource"]["layerId"] = cloned_service['layer_id_mapping'][dataset["dataSource"]["layerId"]]
                            # update the item id
                            dataset["dataSource"]["itemId"] = clone_mapping['Item IDs'][dataset["dataSource"]["itemId"]]

        if "headerPanel" in app_json and "selectors" in app_json["headerPanel"]:
            for selector in app_json["headerPanel"]["selectors"]:
                if "datasets" in selector:
                    for dataset in selector["datasets"]:
                        if "dataSource" in dataset and "itemId" in dataset["dataSource"]:
                            # in some cases the layer ids may have changed when cloning
                            # so we can use a mapping between the old and new to update it
                            for url, cloned_service in clone_mapping['Services'].items():
                                if cloned_service['id'] == clone_mapping['Item IDs'][dataset["dataSource"]["itemId"]]:
                                    # update the layer id
                                    dataset["dataSource"]["layerId"] = cloned_service['layer_id_mapping'][dataset["dataSource"]["layerId"]]
                            # update the item id
                            dataset["dataSource"]["itemId"] = clone_mapping['Item IDs'][dataset["dataSource"]["itemId"]]

        if "leftPanel" in app_json and "selectors" in app_json["leftPanel"]:
            for selector in app_json["leftPanel"]["selectors"]:
                if "datasets" in selector:
                    for dataset in selector["datasets"]:
                        if "dataSource" in dataset and "itemId" in dataset["dataSource"]:
                            # in some cases the layer ids may have changed when cloning
                            # so we can use a mapping between the old and new to update it
                            for url, cloned_service in clone_mapping['Services'].items():
                                if cloned_service['id'] == clone_mapping['Item IDs'][dataset["dataSource"]["itemId"]]:
                                    # update the layer id
                                    dataset["dataSource"]["layerId"] = cloned_service['layer_id_mapping'][dataset["dataSource"]["layerId"]]
                            # update the item id
                            dataset["dataSource"]["itemId"] = clone_mapping['Item IDs'][dataset["dataSource"]["itemId"]]
```

**Comment by chris-fox** [comment]
I think the issue is right now this variable is equivalent to the entire Feature Service:

{ab766cba0dd44ec080420acc10990282}

What I am saying is we need unique variables for every layer/table within a feature service. The way we have constructed it now it works very well when we are always creating all the layers and views. We need to allow users providing their own layers which may be organized differently then our original feature services. I would like for certain solutions allowing users to optionally provide their own layers, if they don't we spin up the services for them.

This is the way the Hub initiative templates currently work and I think we need to follow this pattern to support both patterns,

**Comment by chris-fox** [comment]
@jmhauck 

With the new pattern I am seeing the following in the template:

"dataSource": {
   "type": "featureServiceDataSource",
   "itemId": "{{33298a2612ba4899adc41180c435425f.itemId}}",
   "layerId": 0,
   "table": false
}

Instead of resolving the item id from the Feature Service in general, we should get it from the layer as the layer may be in different feature services. We should add a variable for the layerId as well, because the id may change.

"dataSource": {
   "type": "featureServiceDataSource",
   "itemId": "{{33298a2612ba4899adc41180c435425f.layer0.itemId}}",
   "layerId": {{33298a2612ba4899adc41180c435425f.layer0.layerId}},
   "table": false
}

**Comment by chris-fox** [comment]
@jmhauck, i tested this and found that the template is being created properly but when deployed the variable for the layerId isn't being replaced in the json. For example this is the result:

                        "type": "serviceDataset",
                        "dataSource": {
                            "type": "featureServiceDataSource",
                            "itemId": "5a2a47a0f659453899fad35af506822d",
                            "layerId": "{{e6f6f748903e4528b004b7c2e4136073.layer0.layerId}}",
                            "table": false
                        },

You can reproduce this with the Election Results solution in the deployment app.

**Comment by jmhauck** [comment]
@chris-fox I see...for layerId = 0 it must be evaluated as false somewhere down in adlib...will look at the options

This shows **1**
```html
<!DOCTYPE html>
<html>
<body>
<script src="https://unpkg.com/adlib"></script>
<script>
    alert(adlib.adlib({id: '{{id}}'}, {id: 1}).id)
</script>
</body>
</html>
```

This shows **{{id}}**
```html
<!DOCTYPE html>
<html>
<body>
<script src="https://unpkg.com/adlib"></script>
<script>
    alert(adlib.adlib({id: '{{id}}'}, {id: 0}).id)
</script>
</body>
</html>
```

**Comment by jmhauck** [comment]
I submitted a PR to adlib...we'll see if they take it

**Comment by jmhauck** [comment]
The PR was merged today

**Comment by chris-fox** [comment]
Verified.
