### ISSUE TITLE
Election Management solution failing to create

### ISSUE THREAD

**Issue by chris-fox** [Esri/solution.js#87]
Using the Create application I am logging into the Local Gov Deployment org and attempting to create a solution for Election Management. It gets about 90% through the creation and then stops. Looking at the debugger I don't see any error reported in the Console or any failed requests. Not sure what is causing this issue, but something unique about this one is it has a Workforce Project.

http://ec2-18-219-57-96.us-east-2.compute.amazonaws.com/create/#

**Comment by jmhauck** [comment]
@chris-fox this failure no longer occurs. Two things I see after create though is that it will fail on deploy due to the need for circular dependecy support and that the item display is not correct as it doesn't handle circular dependencies either. Will log an issue in for the portal app for this.

**Comment by chris-fox** [comment]
Verified
